/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for DownloadRequest
 */
public class DownloadRequestTest {
    private final DownloadRequest model = new DownloadRequest();

    /**
     * Model tests for DownloadRequest
     */
    @Test
    public void testDownloadRequest() {
        // TODO: test DownloadRequest
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    public void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'subFormat'
     */
    @Test
    public void subFormatTest() {
        // TODO: test subFormat
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

    /**
     * Test the property 'inFps'
     */
    @Test
    public void inFpsTest() {
        // TODO: test inFps
    }

    /**
     * Test the property 'outFps'
     */
    @Test
    public void outFpsTest() {
        // TODO: test outFps
    }

    /**
     * Test the property 'timeshift'
     */
    @Test
    public void timeshiftTest() {
        // TODO: test timeshift
    }

    /**
     * Test the property 'forceDownload'
     */
    @Test
    public void forceDownloadTest() {
        // TODO: test forceDownload
    }

}
