/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for Features200Response
 */
public class Features200ResponseTest {
    private final Features200Response model = new Features200Response();

    /**
     * Model tests for Features200Response
     */
    @Test
    public void testFeatures200Response() {
        // TODO: test Features200Response
    }

    /**
     * Test the property 'movie'
     */
    @Test
    public void movieTest() {
        // TODO: test movie
    }

    /**
     * Test the property 'episode'
     */
    @Test
    public void episodeTest() {
        // TODO: test episode
    }

    /**
     * Test the property 'tv'
     */
    @Test
    public void tvTest() {
        // TODO: test tv
    }

}
