/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for FeatureTvshowAttributesSeasonsInnerEpisodesInner
 */
public class FeatureTvshowAttributesSeasonsInnerEpisodesInnerTest {
    private final FeatureTvshowAttributesSeasonsInnerEpisodesInner model = new FeatureTvshowAttributesSeasonsInnerEpisodesInner();

    /**
     * Model tests for FeatureTvshowAttributesSeasonsInnerEpisodesInner
     */
    @Test
    public void testFeatureTvshowAttributesSeasonsInnerEpisodesInner() {
        // TODO: test FeatureTvshowAttributesSeasonsInnerEpisodesInner
    }

    /**
     * Test the property 'episodeNumber'
     */
    @Test
    public void episodeNumberTest() {
        // TODO: test episodeNumber
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'featureId'
     */
    @Test
    public void featureIdTest() {
        // TODO: test featureId
    }

    /**
     * Test the property 'featureImdbId'
     */
    @Test
    public void featureImdbIdTest() {
        // TODO: test featureImdbId
    }

}
