/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for FeatureEpisodeAttributes
 */
public class FeatureEpisodeAttributesTest {
    private final FeatureEpisodeAttributes model = new FeatureEpisodeAttributes();

    /**
     * Model tests for FeatureEpisodeAttributes
     */
    @Test
    public void testFeatureEpisodeAttributes() {
        // TODO: test FeatureEpisodeAttributes
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'originalTitle'
     */
    @Test
    public void originalTitleTest() {
        // TODO: test originalTitle
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'parentImdbId'
     */
    @Test
    public void parentImdbIdTest() {
        // TODO: test parentImdbId
    }

    /**
     * Test the property 'parentTitle'
     */
    @Test
    public void parentTitleTest() {
        // TODO: test parentTitle
    }

    /**
     * Test the property 'seasonNumber'
     */
    @Test
    public void seasonNumberTest() {
        // TODO: test seasonNumber
    }

    /**
     * Test the property 'episodeNumber'
     */
    @Test
    public void episodeNumberTest() {
        // TODO: test episodeNumber
    }

    /**
     * Test the property 'imdbId'
     */
    @Test
    public void imdbIdTest() {
        // TODO: test imdbId
    }

    /**
     * Test the property 'tmdbId'
     */
    @Test
    public void tmdbIdTest() {
        // TODO: test tmdbId
    }

    /**
     * Test the property 'titleAka'
     */
    @Test
    public void titleAkaTest() {
        // TODO: test titleAka
    }

    /**
     * Test the property 'featureId'
     */
    @Test
    public void featureIdTest() {
        // TODO: test featureId
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'imgUrl'
     */
    @Test
    public void imgUrlTest() {
        // TODO: test imgUrl
    }

    /**
     * Test the property 'subtitlesCounts'
     */
    @Test
    public void subtitlesCountsTest() {
        // TODO: test subtitlesCounts
    }

    /**
     * Test the property 'subtitlesCount'
     */
    @Test
    public void subtitlesCountTest() {
        // TODO: test subtitlesCount
    }

}
