/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for FeatureTvshowAttributesSeasonsInner
 */
public class FeatureTvshowAttributesSeasonsInnerTest {
    private final FeatureTvshowAttributesSeasonsInner model = new FeatureTvshowAttributesSeasonsInner();

    /**
     * Model tests for FeatureTvshowAttributesSeasonsInner
     */
    @Test
    public void testFeatureTvshowAttributesSeasonsInner() {
        // TODO: test FeatureTvshowAttributesSeasonsInner
    }

    /**
     * Test the property 'seasonNumber'
     */
    @Test
    public void seasonNumberTest() {
        // TODO: test seasonNumber
    }

    /**
     * Test the property 'episodes'
     */
    @Test
    public void episodesTest() {
        // TODO: test episodes
    }

}
