/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for Formats200ResponseData
 */
public class Formats200ResponseDataTest {
    private final Formats200ResponseData model = new Formats200ResponseData();

    /**
     * Model tests for Formats200ResponseData
     */
    @Test
    public void testFormats200ResponseData() {
        // TODO: test Formats200ResponseData
    }

    /**
     * Test the property 'outputFormats'
     */
    @Test
    public void outputFormatsTest() {
        // TODO: test outputFormats
    }

}
