/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for Guessit200Response
 */
public class Guessit200ResponseTest {
    private final Guessit200Response model = new Guessit200Response();

    /**
     * Model tests for Guessit200Response
     */
    @Test
    public void testGuessit200Response() {
        // TODO: test Guessit200Response
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'subtitleLanguage'
     */
    @Test
    public void subtitleLanguageTest() {
        // TODO: test subtitleLanguage
    }

    /**
     * Test the property 'screenSize'
     */
    @Test
    public void screenSizeTest() {
        // TODO: test screenSize
    }

    /**
     * Test the property 'streamingService'
     */
    @Test
    public void streamingServiceTest() {
        // TODO: test streamingService
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'other'
     */
    @Test
    public void otherTest() {
        // TODO: test other
    }

    /**
     * Test the property 'audioCodec'
     */
    @Test
    public void audioCodecTest() {
        // TODO: test audioCodec
    }

    /**
     * Test the property 'audioChannels'
     */
    @Test
    public void audioChannelsTest() {
        // TODO: test audioChannels
    }

    /**
     * Test the property 'videoCodec'
     */
    @Test
    public void videoCodecTest() {
        // TODO: test videoCodec
    }

    /**
     * Test the property 'releaseGroup'
     */
    @Test
    public void releaseGroupTest() {
        // TODO: test releaseGroup
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
