/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for Languages200ResponseDataInner
 */
public class Languages200ResponseDataInnerTest {
    private final Languages200ResponseDataInner model = new Languages200ResponseDataInner();

    /**
     * Model tests for Languages200ResponseDataInner
     */
    @Test
    public void testLanguages200ResponseDataInner() {
        // TODO: test Languages200ResponseDataInner
    }

    /**
     * Test the property 'languageCode'
     */
    @Test
    public void languageCodeTest() {
        // TODO: test languageCode
    }

    /**
     * Test the property 'languageName'
     */
    @Test
    public void languageNameTest() {
        // TODO: test languageName
    }

}
