/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for Latest200ResponseDataInnerAttributesRelatedLinks
 */
public class Latest200ResponseDataInnerAttributesRelatedLinksTest {
    private final Latest200ResponseDataInnerAttributesRelatedLinks model = new Latest200ResponseDataInnerAttributesRelatedLinks();

    /**
     * Model tests for Latest200ResponseDataInnerAttributesRelatedLinks
     */
    @Test
    public void testLatest200ResponseDataInnerAttributesRelatedLinks() {
        // TODO: test Latest200ResponseDataInnerAttributesRelatedLinks
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'imgUrl'
     */
    @Test
    public void imgUrlTest() {
        // TODO: test imgUrl
    }

}
