/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for Login200ResponseUser
 */
public class Login200ResponseUserTest {
    private final Login200ResponseUser model = new Login200ResponseUser();

    /**
     * Model tests for Login200ResponseUser
     */
    @Test
    public void testLogin200ResponseUser() {
        // TODO: test Login200ResponseUser
    }

    /**
     * Test the property 'allowedTranslations'
     */
    @Test
    public void allowedTranslationsTest() {
        // TODO: test allowedTranslations
    }

    /**
     * Test the property 'allowedDownloads'
     */
    @Test
    public void allowedDownloadsTest() {
        // TODO: test allowedDownloads
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'extInstalled'
     */
    @Test
    public void extInstalledTest() {
        // TODO: test extInstalled
    }

    /**
     * Test the property 'vip'
     */
    @Test
    public void vipTest() {
        // TODO: test vip
    }

}
