/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for SubtitleAttributesFeatureDetails
 */
public class SubtitleAttributesFeatureDetailsTest {
    private final SubtitleAttributesFeatureDetails model = new SubtitleAttributesFeatureDetails();

    /**
     * Model tests for SubtitleAttributesFeatureDetails
     */
    @Test
    public void testSubtitleAttributesFeatureDetails() {
        // TODO: test SubtitleAttributesFeatureDetails
    }

    /**
     * Test the property 'featureId'
     */
    @Test
    public void featureIdTest() {
        // TODO: test featureId
    }

    /**
     * Test the property 'featureType'
     */
    @Test
    public void featureTypeTest() {
        // TODO: test featureType
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'movieName'
     */
    @Test
    public void movieNameTest() {
        // TODO: test movieName
    }

    /**
     * Test the property 'imdbId'
     */
    @Test
    public void imdbIdTest() {
        // TODO: test imdbId
    }

    /**
     * Test the property 'tmdbId'
     */
    @Test
    public void tmdbIdTest() {
        // TODO: test tmdbId
    }

}
