/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for SubtitleAttributesFilesInner
 */
public class SubtitleAttributesFilesInnerTest {
    private final SubtitleAttributesFilesInner model = new SubtitleAttributesFilesInner();

    /**
     * Model tests for SubtitleAttributesFilesInner
     */
    @Test
    public void testSubtitleAttributesFilesInner() {
        // TODO: test SubtitleAttributesFilesInner
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    public void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'cdNumber'
     */
    @Test
    public void cdNumberTest() {
        // TODO: test cdNumber
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

    /**
     * Test the property ''
     */
    @Test
    public void Test() {
        // TODO: test
    }

}
