/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for SubtitleAttributesUploader
 */
public class SubtitleAttributesUploaderTest {
    private final SubtitleAttributesUploader model = new SubtitleAttributesUploader();

    /**
     * Model tests for SubtitleAttributesUploader
     */
    @Test
    public void testSubtitleAttributesUploader() {
        // TODO: test SubtitleAttributesUploader
    }

    /**
     * Test the property 'uploaderId'
     */
    @Test
    public void uploaderIdTest() {
        // TODO: test uploaderId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'rank'
     */
    @Test
    public void rankTest() {
        // TODO: test rank
    }

}
