/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import org.junit.Test;


/**
 * Model tests for Userinfo200Response
 */
public class Userinfo200ResponseTest {
    private final Userinfo200Response model = new Userinfo200Response();

    /**
     * Model tests for Userinfo200Response
     */
    @Test
    public void testUserinfo200Response() {
        // TODO: test Userinfo200Response
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
