/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Download200Response
 */
public class Download200ResponseTest {
    private final Download200Response model = new Download200Response();

    /**
     * Model tests for Download200Response
     */
    @Test
    public void testDownload200Response() {
        // TODO: test Download200Response
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

    /**
     * Test the property 'requests'
     */
    @Test
    public void requestsTest() {
        // TODO: test requests
    }

    /**
     * Test the property 'remaining'
     */
    @Test
    public void remainingTest() {
        // TODO: test remaining
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'resetTime'
     */
    @Test
    public void resetTimeTest() {
        // TODO: test resetTime
    }

    /**
     * Test the property 'resetTimeUtc'
     */
    @Test
    public void resetTimeUtcTest() {
        // TODO: test resetTimeUtc
    }

}
