/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.openapitools.client.model.FeatureTvshowAttributesSeasonsInner;
import org.openapitools.client.model.FeatureTvshowAttributesSubtitlesCounts;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FeatureTvshowAttributes
 */
public class FeatureTvshowAttributesTest {
    private final FeatureTvshowAttributes model = new FeatureTvshowAttributes();

    /**
     * Model tests for FeatureTvshowAttributes
     */
    @Test
    public void testFeatureTvshowAttributes() {
        // TODO: test FeatureTvshowAttributes
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'originalTitle'
     */
    @Test
    public void originalTitleTest() {
        // TODO: test originalTitle
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'imdbId'
     */
    @Test
    public void imdbIdTest() {
        // TODO: test imdbId
    }

    /**
     * Test the property 'tmdbId'
     */
    @Test
    public void tmdbIdTest() {
        // TODO: test tmdbId
    }

    /**
     * Test the property 'titleAka'
     */
    @Test
    public void titleAkaTest() {
        // TODO: test titleAka
    }

    /**
     * Test the property 'featureId'
     */
    @Test
    public void featureIdTest() {
        // TODO: test featureId
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'imgUrl'
     */
    @Test
    public void imgUrlTest() {
        // TODO: test imgUrl
    }

    /**
     * Test the property 'subtitlesCounts'
     */
    @Test
    public void subtitlesCountsTest() {
        // TODO: test subtitlesCounts
    }

    /**
     * Test the property 'subtitlesCount'
     */
    @Test
    public void subtitlesCountTest() {
        // TODO: test subtitlesCount
    }

    /**
     * Test the property 'seasons'
     */
    @Test
    public void seasonsTest() {
        // TODO: test seasons
    }

}
