/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FeatureEpisodeAttributesSubtitlesCounts
 */
public class FeatureEpisodeAttributesSubtitlesCountsTest {
    private final FeatureEpisodeAttributesSubtitlesCounts model = new FeatureEpisodeAttributesSubtitlesCounts();

    /**
     * Model tests for FeatureEpisodeAttributesSubtitlesCounts
     */
    @Test
    public void testFeatureEpisodeAttributesSubtitlesCounts() {
        // TODO: test FeatureEpisodeAttributesSubtitlesCounts
    }

    /**
     * Test the property 'pl'
     */
    @Test
    public void plTest() {
        // TODO: test pl
    }

    /**
     * Test the property 'en'
     */
    @Test
    public void enTest() {
        // TODO: test en
    }

    /**
     * Test the property 'ptBR'
     */
    @Test
    public void ptBRTest() {
        // TODO: test ptBR
    }

    /**
     * Test the property 'es'
     */
    @Test
    public void esTest() {
        // TODO: test es
    }

    /**
     * Test the property 'ro'
     */
    @Test
    public void roTest() {
        // TODO: test ro
    }

    /**
     * Test the property 'nl'
     */
    @Test
    public void nlTest() {
        // TODO: test nl
    }

    /**
     * Test the property 'tr'
     */
    @Test
    public void trTest() {
        // TODO: test tr
    }

    /**
     * Test the property 'he'
     */
    @Test
    public void heTest() {
        // TODO: test he
    }

    /**
     * Test the property 'ptPT'
     */
    @Test
    public void ptPTTest() {
        // TODO: test ptPT
    }

    /**
     * Test the property 'cs'
     */
    @Test
    public void csTest() {
        // TODO: test cs
    }

    /**
     * Test the property 'fi'
     */
    @Test
    public void fiTest() {
        // TODO: test fi
    }

    /**
     * Test the property 'hu'
     */
    @Test
    public void huTest() {
        // TODO: test hu
    }

    /**
     * Test the property 'ar'
     */
    @Test
    public void arTest() {
        // TODO: test ar
    }

    /**
     * Test the property 'bg'
     */
    @Test
    public void bgTest() {
        // TODO: test bg
    }

    /**
     * Test the property 'fr'
     */
    @Test
    public void frTest() {
        // TODO: test fr
    }

    /**
     * Test the property 'sl'
     */
    @Test
    public void slTest() {
        // TODO: test sl
    }

    /**
     * Test the property 'el'
     */
    @Test
    public void elTest() {
        // TODO: test el
    }

    /**
     * Test the property 'hr'
     */
    @Test
    public void hrTest() {
        // TODO: test hr
    }

    /**
     * Test the property 'sr'
     */
    @Test
    public void srTest() {
        // TODO: test sr
    }

    /**
     * Test the property 'et'
     */
    @Test
    public void etTest() {
        // TODO: test et
    }

    /**
     * Test the property 'sv'
     */
    @Test
    public void svTest() {
        // TODO: test sv
    }

    /**
     * Test the property 'th'
     */
    @Test
    public void thTest() {
        // TODO: test th
    }

    /**
     * Test the property 'bs'
     */
    @Test
    public void bsTest() {
        // TODO: test bs
    }

    /**
     * Test the property 'da'
     */
    @Test
    public void daTest() {
        // TODO: test da
    }

    /**
     * Test the property 'de'
     */
    @Test
    public void deTest() {
        // TODO: test de
    }

    /**
     * Test the property 'mk'
     */
    @Test
    public void mkTest() {
        // TODO: test mk
    }

    /**
     * Test the property 'no'
     */
    @Test
    public void noTest() {
        // TODO: test no
    }

    /**
     * Test the property 'ru'
     */
    @Test
    public void ruTest() {
        // TODO: test ru
    }

}
