/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.LinkedHashSet;
import java.util.Set;
import org.openapitools.client.model.FeatureTvshowAttributesSeasonsInnerEpisodesInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FeatureTvshowAttributesSeasonsInner
 */
public class FeatureTvshowAttributesSeasonsInnerTest {
    private final FeatureTvshowAttributesSeasonsInner model = new FeatureTvshowAttributesSeasonsInner();

    /**
     * Model tests for FeatureTvshowAttributesSeasonsInner
     */
    @Test
    public void testFeatureTvshowAttributesSeasonsInner() {
        // TODO: test FeatureTvshowAttributesSeasonsInner
    }

    /**
     * Test the property 'seasonNumber'
     */
    @Test
    public void seasonNumberTest() {
        // TODO: test seasonNumber
    }

    /**
     * Test the property 'episodes'
     */
    @Test
    public void episodesTest() {
        // TODO: test episodes
    }

}
