/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Formats200ResponseData
 */
public class Formats200ResponseDataTest {
    private final Formats200ResponseData model = new Formats200ResponseData();

    /**
     * Model tests for Formats200ResponseData
     */
    @Test
    public void testFormats200ResponseData() {
        // TODO: test Formats200ResponseData
    }

    /**
     * Test the property 'outputFormats'
     */
    @Test
    public void outputFormatsTest() {
        // TODO: test outputFormats
    }

}
