/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Latest200ResponseDataInnerAttributesFilesInner
 */
public class Latest200ResponseDataInnerAttributesFilesInnerTest {
    private final Latest200ResponseDataInnerAttributesFilesInner model = new Latest200ResponseDataInnerAttributesFilesInner();

    /**
     * Model tests for Latest200ResponseDataInnerAttributesFilesInner
     */
    @Test
    public void testLatest200ResponseDataInnerAttributesFilesInner() {
        // TODO: test Latest200ResponseDataInnerAttributesFilesInner
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    public void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'cdNumber'
     */
    @Test
    public void cdNumberTest() {
        // TODO: test cdNumber
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

}
