/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubtitleAttributesUploader
 */
public class SubtitleAttributesUploaderTest {
    private final SubtitleAttributesUploader model = new SubtitleAttributesUploader();

    /**
     * Model tests for SubtitleAttributesUploader
     */
    @Test
    public void testSubtitleAttributesUploader() {
        // TODO: test SubtitleAttributesUploader
    }

    /**
     * Test the property 'uploaderId'
     */
    @Test
    public void uploaderIdTest() {
        // TODO: test uploaderId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'rank'
     */
    @Test
    public void rankTest() {
        // TODO: test rank
    }

}
