/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.openapitools.client.model.SubtitleAttributesFeatureDetails;
import org.openapitools.client.model.SubtitleAttributesFilesInner;
import org.openapitools.client.model.SubtitleAttributesUploader;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubtitleAttributes
 */
public class SubtitleAttributesTest {
    private final SubtitleAttributes model = new SubtitleAttributes();

    /**
     * Model tests for SubtitleAttributes
     */
    @Test
    public void testSubtitleAttributes() {
        // TODO: test SubtitleAttributes
    }

    /**
     * Test the property 'subtitleId'
     */
    @Test
    public void subtitleIdTest() {
        // TODO: test subtitleId
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'downloadCount'
     */
    @Test
    public void downloadCountTest() {
        // TODO: test downloadCount
    }

    /**
     * Test the property 'newDownloadCount'
     */
    @Test
    public void newDownloadCountTest() {
        // TODO: test newDownloadCount
    }

    /**
     * Test the property 'hearingImpaired'
     */
    @Test
    public void hearingImpairedTest() {
        // TODO: test hearingImpaired
    }

    /**
     * Test the property 'hd'
     */
    @Test
    public void hdTest() {
        // TODO: test hd
    }

    /**
     * Test the property 'fps'
     */
    @Test
    public void fpsTest() {
        // TODO: test fps
    }

    /**
     * Test the property 'votes'
     */
    @Test
    public void votesTest() {
        // TODO: test votes
    }

    /**
     * Test the property 'points'
     */
    @Test
    public void pointsTest() {
        // TODO: test points
    }

    /**
     * Test the property 'ratings'
     */
    @Test
    public void ratingsTest() {
        // TODO: test ratings
    }

    /**
     * Test the property 'fromTrusted'
     */
    @Test
    public void fromTrustedTest() {
        // TODO: test fromTrusted
    }

    /**
     * Test the property 'foreignPartsOnly'
     */
    @Test
    public void foreignPartsOnlyTest() {
        // TODO: test foreignPartsOnly
    }

    /**
     * Test the property 'aiTranslated'
     */
    @Test
    public void aiTranslatedTest() {
        // TODO: test aiTranslated
    }

    /**
     * Test the property 'machineTranslated'
     */
    @Test
    public void machineTranslatedTest() {
        // TODO: test machineTranslated
    }

    /**
     * Test the property 'uploadDate'
     */
    @Test
    public void uploadDateTest() {
        // TODO: test uploadDate
    }

    /**
     * Test the property 'release'
     */
    @Test
    public void releaseTest() {
        // TODO: test release
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'legacySubtitleId'
     */
    @Test
    public void legacySubtitleIdTest() {
        // TODO: test legacySubtitleId
    }

    /**
     * Test the property 'uploader'
     */
    @Test
    public void uploaderTest() {
        // TODO: test uploader
    }

    /**
     * Test the property 'featureDetails'
     */
    @Test
    public void featureDetailsTest() {
        // TODO: test featureDetails
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'relatedLinks'
     */
    @Test
    public void relatedLinksTest() {
        // TODO: test relatedLinks
    }

    /**
     * Test the property 'files'
     */
    @Test
    public void filesTest() {
        // TODO: test files
    }

}
