/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Userinfo200ResponseData
 */
public class Userinfo200ResponseDataTest {
    private final Userinfo200ResponseData model = new Userinfo200ResponseData();

    /**
     * Model tests for Userinfo200ResponseData
     */
    @Test
    public void testUserinfo200ResponseData() {
        // TODO: test Userinfo200ResponseData
    }

    /**
     * Test the property 'allowedDownloads'
     */
    @Test
    public void allowedDownloadsTest() {
        // TODO: test allowedDownloads
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'extInstalled'
     */
    @Test
    public void extInstalledTest() {
        // TODO: test extInstalled
    }

    /**
     * Test the property 'vip'
     */
    @Test
    public void vipTest() {
        // TODO: test vip
    }

    /**
     * Test the property 'downloadsCount'
     */
    @Test
    public void downloadsCountTest() {
        // TODO: test downloadsCount
    }

    /**
     * Test the property 'remainingDownloads'
     */
    @Test
    public void remainingDownloadsTest() {
        // TODO: test remainingDownloads
    }

}
