/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * FeatureTvshowAttributes
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-26T20:07:01.076156+02:00[Europe/Amsterdam]")
public class FeatureTvshowAttributes {
  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_ORIGINAL_TITLE = "original_title";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_TITLE)
  private String originalTitle;

  public static final String SERIALIZED_NAME_YEAR = "year";
  @SerializedName(SERIALIZED_NAME_YEAR)
  private String year;

  public static final String SERIALIZED_NAME_IMDB_ID = "imdb_id";
  @SerializedName(SERIALIZED_NAME_IMDB_ID)
  private BigDecimal imdbId;

  public static final String SERIALIZED_NAME_TMDB_ID = "tmdb_id";
  @SerializedName(SERIALIZED_NAME_TMDB_ID)
  private BigDecimal tmdbId;

  public static final String SERIALIZED_NAME_TITLE_AKA = "title_aka";
  @SerializedName(SERIALIZED_NAME_TITLE_AKA)
  private List<Object> titleAka = new ArrayList<>();

  public static final String SERIALIZED_NAME_FEATURE_ID = "feature_id";
  @SerializedName(SERIALIZED_NAME_FEATURE_ID)
  private String featureId;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_IMG_URL = "img_url";
  @SerializedName(SERIALIZED_NAME_IMG_URL)
  private String imgUrl;

  public static final String SERIALIZED_NAME_SUBTITLES_COUNTS = "subtitles_counts";
  @SerializedName(SERIALIZED_NAME_SUBTITLES_COUNTS)
  private FeatureTvshowAttributesSubtitlesCounts subtitlesCounts;

  public static final String SERIALIZED_NAME_SUBTITLES_COUNT = "subtitles_count";
  @SerializedName(SERIALIZED_NAME_SUBTITLES_COUNT)
  private BigDecimal subtitlesCount;

  public static final String SERIALIZED_NAME_SEASONS = "seasons";
  @SerializedName(SERIALIZED_NAME_SEASONS)
  private Set<FeatureTvshowAttributesSeasonsInner> seasons = new LinkedHashSet<>();

  public FeatureTvshowAttributes() {
  }

  public FeatureTvshowAttributes title(String title) {

    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nonnull

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public FeatureTvshowAttributes originalTitle(String originalTitle) {

    this.originalTitle = originalTitle;
    return this;
  }

   /**
   * Get originalTitle
   * @return originalTitle
  **/
  @javax.annotation.Nonnull

  public String getOriginalTitle() {
    return originalTitle;
  }


  public void setOriginalTitle(String originalTitle) {
    this.originalTitle = originalTitle;
  }


  public FeatureTvshowAttributes year(String year) {

    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @javax.annotation.Nonnull

  public String getYear() {
    return year;
  }


  public void setYear(String year) {
    this.year = year;
  }


  public FeatureTvshowAttributes imdbId(BigDecimal imdbId) {

    this.imdbId = imdbId;
    return this;
  }

   /**
   * Get imdbId
   * @return imdbId
  **/
  @javax.annotation.Nonnull

  public BigDecimal getImdbId() {
    return imdbId;
  }


  public void setImdbId(BigDecimal imdbId) {
    this.imdbId = imdbId;
  }


  public FeatureTvshowAttributes tmdbId(BigDecimal tmdbId) {

    this.tmdbId = tmdbId;
    return this;
  }

   /**
   * Get tmdbId
   * @return tmdbId
  **/
  @javax.annotation.Nonnull

  public BigDecimal getTmdbId() {
    return tmdbId;
  }


  public void setTmdbId(BigDecimal tmdbId) {
    this.tmdbId = tmdbId;
  }


  public FeatureTvshowAttributes titleAka(List<Object> titleAka) {

    this.titleAka = titleAka;
    return this;
  }

  public FeatureTvshowAttributes addTitleAkaItem(Object titleAkaItem) {
    if (this.titleAka == null) {
      this.titleAka = new ArrayList<>();
    }
    this.titleAka.add(titleAkaItem);
    return this;
  }

   /**
   * Get titleAka
   * @return titleAka
  **/
  @javax.annotation.Nonnull

  public List<Object> getTitleAka() {
    return titleAka;
  }


  public void setTitleAka(List<Object> titleAka) {
    this.titleAka = titleAka;
  }


  public FeatureTvshowAttributes featureId(String featureId) {

    this.featureId = featureId;
    return this;
  }

   /**
   * Get featureId
   * @return featureId
  **/
  @javax.annotation.Nonnull

  public String getFeatureId() {
    return featureId;
  }


  public void setFeatureId(String featureId) {
    this.featureId = featureId;
  }


  public FeatureTvshowAttributes url(String url) {

    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nonnull

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public FeatureTvshowAttributes imgUrl(String imgUrl) {

    this.imgUrl = imgUrl;
    return this;
  }

   /**
   * Get imgUrl
   * @return imgUrl
  **/
  @javax.annotation.Nonnull

  public String getImgUrl() {
    return imgUrl;
  }


  public void setImgUrl(String imgUrl) {
    this.imgUrl = imgUrl;
  }


  public FeatureTvshowAttributes subtitlesCounts(FeatureTvshowAttributesSubtitlesCounts subtitlesCounts) {

    this.subtitlesCounts = subtitlesCounts;
    return this;
  }

   /**
   * Get subtitlesCounts
   * @return subtitlesCounts
  **/
  @javax.annotation.Nonnull

  public FeatureTvshowAttributesSubtitlesCounts getSubtitlesCounts() {
    return subtitlesCounts;
  }


  public void setSubtitlesCounts(FeatureTvshowAttributesSubtitlesCounts subtitlesCounts) {
    this.subtitlesCounts = subtitlesCounts;
  }


  public FeatureTvshowAttributes subtitlesCount(BigDecimal subtitlesCount) {

    this.subtitlesCount = subtitlesCount;
    return this;
  }

   /**
   * Get subtitlesCount
   * @return subtitlesCount
  **/
  @javax.annotation.Nonnull

  public BigDecimal getSubtitlesCount() {
    return subtitlesCount;
  }


  public void setSubtitlesCount(BigDecimal subtitlesCount) {
    this.subtitlesCount = subtitlesCount;
  }


  public FeatureTvshowAttributes seasons(Set<FeatureTvshowAttributesSeasonsInner> seasons) {

    this.seasons = seasons;
    return this;
  }

  public FeatureTvshowAttributes addSeasonsItem(FeatureTvshowAttributesSeasonsInner seasonsItem) {
    if (this.seasons == null) {
      this.seasons = new LinkedHashSet<>();
    }
    this.seasons.add(seasonsItem);
    return this;
  }

   /**
   * Get seasons
   * @return seasons
  **/
  @javax.annotation.Nonnull

  public Set<FeatureTvshowAttributesSeasonsInner> getSeasons() {
    return seasons;
  }


  public void setSeasons(Set<FeatureTvshowAttributesSeasonsInner> seasons) {
    this.seasons = seasons;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeatureTvshowAttributes featureTvshowAttributes = (FeatureTvshowAttributes) o;
    return Objects.equals(this.title, featureTvshowAttributes.title) &&
        Objects.equals(this.originalTitle, featureTvshowAttributes.originalTitle) &&
        Objects.equals(this.year, featureTvshowAttributes.year) &&
        Objects.equals(this.imdbId, featureTvshowAttributes.imdbId) &&
        Objects.equals(this.tmdbId, featureTvshowAttributes.tmdbId) &&
        Objects.equals(this.titleAka, featureTvshowAttributes.titleAka) &&
        Objects.equals(this.featureId, featureTvshowAttributes.featureId) &&
        Objects.equals(this.url, featureTvshowAttributes.url) &&
        Objects.equals(this.imgUrl, featureTvshowAttributes.imgUrl) &&
        Objects.equals(this.subtitlesCounts, featureTvshowAttributes.subtitlesCounts) &&
        Objects.equals(this.subtitlesCount, featureTvshowAttributes.subtitlesCount) &&
        Objects.equals(this.seasons, featureTvshowAttributes.seasons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, originalTitle, year, imdbId, tmdbId, titleAka, featureId, url, imgUrl, subtitlesCounts, subtitlesCount, seasons);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeatureTvshowAttributes {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    originalTitle: ").append(toIndentedString(originalTitle)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    imdbId: ").append(toIndentedString(imdbId)).append("\n");
    sb.append("    tmdbId: ").append(toIndentedString(tmdbId)).append("\n");
    sb.append("    titleAka: ").append(toIndentedString(titleAka)).append("\n");
    sb.append("    featureId: ").append(toIndentedString(featureId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    imgUrl: ").append(toIndentedString(imgUrl)).append("\n");
    sb.append("    subtitlesCounts: ").append(toIndentedString(subtitlesCounts)).append("\n");
    sb.append("    subtitlesCount: ").append(toIndentedString(subtitlesCount)).append("\n");
    sb.append("    seasons: ").append(toIndentedString(seasons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

