/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * FeatureMovieAttributes
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-26T20:07:01.076156+02:00[Europe/Amsterdam]")
public class FeatureMovieAttributes {
  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_ORIGINAL_TITLE = "original_title";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_TITLE)
  private String originalTitle;

  public static final String SERIALIZED_NAME_YEAR = "year";
  @SerializedName(SERIALIZED_NAME_YEAR)
  private String year;

  public static final String SERIALIZED_NAME_SUBTITLES_COUNTS = "subtitles_counts";
  @SerializedName(SERIALIZED_NAME_SUBTITLES_COUNTS)
  private FeatureMovieAttributesSubtitlesCounts subtitlesCounts;

  public static final String SERIALIZED_NAME_SUBTITLES_COUNT = "subtitles_count";
  @SerializedName(SERIALIZED_NAME_SUBTITLES_COUNT)
  private BigDecimal subtitlesCount;

  public static final String SERIALIZED_NAME_SEASONS_COUNT = "seasons_count";
  @SerializedName(SERIALIZED_NAME_SEASONS_COUNT)
  private BigDecimal seasonsCount;

  public static final String SERIALIZED_NAME_PARENT_TITLE = "parent_title";
  @SerializedName(SERIALIZED_NAME_PARENT_TITLE)
  private String parentTitle;

  public static final String SERIALIZED_NAME_SEASON_NUMBER = "season_number";
  @SerializedName(SERIALIZED_NAME_SEASON_NUMBER)
  private BigDecimal seasonNumber;

  public static final String SERIALIZED_NAME_EPISODE_NUMBER = "episode_number";
  @SerializedName(SERIALIZED_NAME_EPISODE_NUMBER)
  private Object episodeNumber;

  public static final String SERIALIZED_NAME_IMDB_ID = "imdb_id";
  @SerializedName(SERIALIZED_NAME_IMDB_ID)
  private BigDecimal imdbId;

  public static final String SERIALIZED_NAME_TMDB_ID = "tmdb_id";
  @SerializedName(SERIALIZED_NAME_TMDB_ID)
  private BigDecimal tmdbId;

  public static final String SERIALIZED_NAME_PARENT_IMDB_ID = "parent_imdb_id";
  @SerializedName(SERIALIZED_NAME_PARENT_IMDB_ID)
  private Object parentImdbId;

  public static final String SERIALIZED_NAME_FEATURE_ID = "feature_id";
  @SerializedName(SERIALIZED_NAME_FEATURE_ID)
  private String featureId;

  public static final String SERIALIZED_NAME_TITLE_AKA = "title_aka";
  @SerializedName(SERIALIZED_NAME_TITLE_AKA)
  private List<Object> titleAka = new ArrayList<>();

  public static final String SERIALIZED_NAME_FEATURE_TYPE = "feature_type";
  @SerializedName(SERIALIZED_NAME_FEATURE_TYPE)
  private String featureType;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_IMG_URL = "img_url";
  @SerializedName(SERIALIZED_NAME_IMG_URL)
  private String imgUrl;

  public FeatureMovieAttributes() {
  }

  public FeatureMovieAttributes title(String title) {

    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nonnull

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public FeatureMovieAttributes originalTitle(String originalTitle) {

    this.originalTitle = originalTitle;
    return this;
  }

   /**
   * Get originalTitle
   * @return originalTitle
  **/
  @javax.annotation.Nonnull

  public String getOriginalTitle() {
    return originalTitle;
  }


  public void setOriginalTitle(String originalTitle) {
    this.originalTitle = originalTitle;
  }


  public FeatureMovieAttributes year(String year) {

    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @javax.annotation.Nonnull

  public String getYear() {
    return year;
  }


  public void setYear(String year) {
    this.year = year;
  }


  public FeatureMovieAttributes subtitlesCounts(FeatureMovieAttributesSubtitlesCounts subtitlesCounts) {

    this.subtitlesCounts = subtitlesCounts;
    return this;
  }

   /**
   * Get subtitlesCounts
   * @return subtitlesCounts
  **/
  @javax.annotation.Nonnull

  public FeatureMovieAttributesSubtitlesCounts getSubtitlesCounts() {
    return subtitlesCounts;
  }


  public void setSubtitlesCounts(FeatureMovieAttributesSubtitlesCounts subtitlesCounts) {
    this.subtitlesCounts = subtitlesCounts;
  }


  public FeatureMovieAttributes subtitlesCount(BigDecimal subtitlesCount) {

    this.subtitlesCount = subtitlesCount;
    return this;
  }

   /**
   * Get subtitlesCount
   * @return subtitlesCount
  **/
  @javax.annotation.Nonnull

  public BigDecimal getSubtitlesCount() {
    return subtitlesCount;
  }


  public void setSubtitlesCount(BigDecimal subtitlesCount) {
    this.subtitlesCount = subtitlesCount;
  }


  public FeatureMovieAttributes seasonsCount(BigDecimal seasonsCount) {

    this.seasonsCount = seasonsCount;
    return this;
  }

   /**
   * Get seasonsCount
   * @return seasonsCount
  **/
  @javax.annotation.Nonnull

  public BigDecimal getSeasonsCount() {
    return seasonsCount;
  }


  public void setSeasonsCount(BigDecimal seasonsCount) {
    this.seasonsCount = seasonsCount;
  }


  public FeatureMovieAttributes parentTitle(String parentTitle) {

    this.parentTitle = parentTitle;
    return this;
  }

   /**
   * Get parentTitle
   * @return parentTitle
  **/
  @javax.annotation.Nonnull

  public String getParentTitle() {
    return parentTitle;
  }


  public void setParentTitle(String parentTitle) {
    this.parentTitle = parentTitle;
  }


  public FeatureMovieAttributes seasonNumber(BigDecimal seasonNumber) {

    this.seasonNumber = seasonNumber;
    return this;
  }

   /**
   * Get seasonNumber
   * @return seasonNumber
  **/
  @javax.annotation.Nonnull

  public BigDecimal getSeasonNumber() {
    return seasonNumber;
  }


  public void setSeasonNumber(BigDecimal seasonNumber) {
    this.seasonNumber = seasonNumber;
  }


  public FeatureMovieAttributes episodeNumber(Object episodeNumber) {

    this.episodeNumber = episodeNumber;
    return this;
  }

   /**
   * Get episodeNumber
   * @return episodeNumber
  **/
  @javax.annotation.Nullable

  public Object getEpisodeNumber() {
    return episodeNumber;
  }


  public void setEpisodeNumber(Object episodeNumber) {
    this.episodeNumber = episodeNumber;
  }


  public FeatureMovieAttributes imdbId(BigDecimal imdbId) {

    this.imdbId = imdbId;
    return this;
  }

   /**
   * Get imdbId
   * @return imdbId
  **/
  @javax.annotation.Nonnull

  public BigDecimal getImdbId() {
    return imdbId;
  }


  public void setImdbId(BigDecimal imdbId) {
    this.imdbId = imdbId;
  }


  public FeatureMovieAttributes tmdbId(BigDecimal tmdbId) {

    this.tmdbId = tmdbId;
    return this;
  }

   /**
   * Get tmdbId
   * @return tmdbId
  **/
  @javax.annotation.Nonnull

  public BigDecimal getTmdbId() {
    return tmdbId;
  }


  public void setTmdbId(BigDecimal tmdbId) {
    this.tmdbId = tmdbId;
  }


  public FeatureMovieAttributes parentImdbId(Object parentImdbId) {

    this.parentImdbId = parentImdbId;
    return this;
  }

   /**
   * Get parentImdbId
   * @return parentImdbId
  **/
  @javax.annotation.Nullable

  public Object getParentImdbId() {
    return parentImdbId;
  }


  public void setParentImdbId(Object parentImdbId) {
    this.parentImdbId = parentImdbId;
  }


  public FeatureMovieAttributes featureId(String featureId) {

    this.featureId = featureId;
    return this;
  }

   /**
   * Get featureId
   * @return featureId
  **/
  @javax.annotation.Nonnull

  public String getFeatureId() {
    return featureId;
  }


  public void setFeatureId(String featureId) {
    this.featureId = featureId;
  }


  public FeatureMovieAttributes titleAka(List<Object> titleAka) {

    this.titleAka = titleAka;
    return this;
  }

  public FeatureMovieAttributes addTitleAkaItem(Object titleAkaItem) {
    if (this.titleAka == null) {
      this.titleAka = new ArrayList<>();
    }
    this.titleAka.add(titleAkaItem);
    return this;
  }

   /**
   * Get titleAka
   * @return titleAka
  **/
  @javax.annotation.Nonnull

  public List<Object> getTitleAka() {
    return titleAka;
  }


  public void setTitleAka(List<Object> titleAka) {
    this.titleAka = titleAka;
  }


  public FeatureMovieAttributes featureType(String featureType) {

    this.featureType = featureType;
    return this;
  }

   /**
   * Get featureType
   * @return featureType
  **/
  @javax.annotation.Nonnull

  public String getFeatureType() {
    return featureType;
  }


  public void setFeatureType(String featureType) {
    this.featureType = featureType;
  }


  public FeatureMovieAttributes url(String url) {

    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nonnull

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public FeatureMovieAttributes imgUrl(String imgUrl) {

    this.imgUrl = imgUrl;
    return this;
  }

   /**
   * Get imgUrl
   * @return imgUrl
  **/
  @javax.annotation.Nonnull

  public String getImgUrl() {
    return imgUrl;
  }


  public void setImgUrl(String imgUrl) {
    this.imgUrl = imgUrl;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeatureMovieAttributes featureMovieAttributes = (FeatureMovieAttributes) o;
    return Objects.equals(this.title, featureMovieAttributes.title) &&
        Objects.equals(this.originalTitle, featureMovieAttributes.originalTitle) &&
        Objects.equals(this.year, featureMovieAttributes.year) &&
        Objects.equals(this.subtitlesCounts, featureMovieAttributes.subtitlesCounts) &&
        Objects.equals(this.subtitlesCount, featureMovieAttributes.subtitlesCount) &&
        Objects.equals(this.seasonsCount, featureMovieAttributes.seasonsCount) &&
        Objects.equals(this.parentTitle, featureMovieAttributes.parentTitle) &&
        Objects.equals(this.seasonNumber, featureMovieAttributes.seasonNumber) &&
        Objects.equals(this.episodeNumber, featureMovieAttributes.episodeNumber) &&
        Objects.equals(this.imdbId, featureMovieAttributes.imdbId) &&
        Objects.equals(this.tmdbId, featureMovieAttributes.tmdbId) &&
        Objects.equals(this.parentImdbId, featureMovieAttributes.parentImdbId) &&
        Objects.equals(this.featureId, featureMovieAttributes.featureId) &&
        Objects.equals(this.titleAka, featureMovieAttributes.titleAka) &&
        Objects.equals(this.featureType, featureMovieAttributes.featureType) &&
        Objects.equals(this.url, featureMovieAttributes.url) &&
        Objects.equals(this.imgUrl, featureMovieAttributes.imgUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, originalTitle, year, subtitlesCounts, subtitlesCount, seasonsCount, parentTitle, seasonNumber, episodeNumber, imdbId, tmdbId, parentImdbId, featureId, titleAka, featureType, url, imgUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeatureMovieAttributes {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    originalTitle: ").append(toIndentedString(originalTitle)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    subtitlesCounts: ").append(toIndentedString(subtitlesCounts)).append("\n");
    sb.append("    subtitlesCount: ").append(toIndentedString(subtitlesCount)).append("\n");
    sb.append("    seasonsCount: ").append(toIndentedString(seasonsCount)).append("\n");
    sb.append("    parentTitle: ").append(toIndentedString(parentTitle)).append("\n");
    sb.append("    seasonNumber: ").append(toIndentedString(seasonNumber)).append("\n");
    sb.append("    episodeNumber: ").append(toIndentedString(episodeNumber)).append("\n");
    sb.append("    imdbId: ").append(toIndentedString(imdbId)).append("\n");
    sb.append("    tmdbId: ").append(toIndentedString(tmdbId)).append("\n");
    sb.append("    parentImdbId: ").append(toIndentedString(parentImdbId)).append("\n");
    sb.append("    featureId: ").append(toIndentedString(featureId)).append("\n");
    sb.append("    titleAka: ").append(toIndentedString(titleAka)).append("\n");
    sb.append("    featureType: ").append(toIndentedString(featureType)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    imgUrl: ").append(toIndentedString(imgUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

