/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;

/**
 * FeatureEpisodeAttributesSubtitlesCounts
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-26T20:07:01.076156+02:00[Europe/Amsterdam]")
public class FeatureEpisodeAttributesSubtitlesCounts {
  public static final String SERIALIZED_NAME_PL = "pl";
  @SerializedName(SERIALIZED_NAME_PL)
  private BigDecimal pl;

  public static final String SERIALIZED_NAME_EN = "en";
  @SerializedName(SERIALIZED_NAME_EN)
  private BigDecimal en;

  public static final String SERIALIZED_NAME_PT_B_R = "pt-BR";
  @SerializedName(SERIALIZED_NAME_PT_B_R)
  private BigDecimal ptBR;

  public static final String SERIALIZED_NAME_ES = "es";
  @SerializedName(SERIALIZED_NAME_ES)
  private BigDecimal es;

  public static final String SERIALIZED_NAME_RO = "ro";
  @SerializedName(SERIALIZED_NAME_RO)
  private BigDecimal ro;

  public static final String SERIALIZED_NAME_NL = "nl";
  @SerializedName(SERIALIZED_NAME_NL)
  private BigDecimal nl;

  public static final String SERIALIZED_NAME_TR = "tr";
  @SerializedName(SERIALIZED_NAME_TR)
  private BigDecimal tr;

  public static final String SERIALIZED_NAME_HE = "he";
  @SerializedName(SERIALIZED_NAME_HE)
  private BigDecimal he;

  public static final String SERIALIZED_NAME_PT_P_T = "pt-PT";
  @SerializedName(SERIALIZED_NAME_PT_P_T)
  private BigDecimal ptPT;

  public static final String SERIALIZED_NAME_CS = "cs";
  @SerializedName(SERIALIZED_NAME_CS)
  private BigDecimal cs;

  public static final String SERIALIZED_NAME_FI = "fi";
  @SerializedName(SERIALIZED_NAME_FI)
  private BigDecimal fi;

  public static final String SERIALIZED_NAME_HU = "hu";
  @SerializedName(SERIALIZED_NAME_HU)
  private BigDecimal hu;

  public static final String SERIALIZED_NAME_AR = "ar";
  @SerializedName(SERIALIZED_NAME_AR)
  private BigDecimal ar;

  public static final String SERIALIZED_NAME_BG = "bg";
  @SerializedName(SERIALIZED_NAME_BG)
  private BigDecimal bg;

  public static final String SERIALIZED_NAME_FR = "fr";
  @SerializedName(SERIALIZED_NAME_FR)
  private BigDecimal fr;

  public static final String SERIALIZED_NAME_SL = "sl";
  @SerializedName(SERIALIZED_NAME_SL)
  private BigDecimal sl;

  public static final String SERIALIZED_NAME_EL = "el";
  @SerializedName(SERIALIZED_NAME_EL)
  private BigDecimal el;

  public static final String SERIALIZED_NAME_HR = "hr";
  @SerializedName(SERIALIZED_NAME_HR)
  private BigDecimal hr;

  public static final String SERIALIZED_NAME_SR = "sr";
  @SerializedName(SERIALIZED_NAME_SR)
  private BigDecimal sr;

  public static final String SERIALIZED_NAME_ET = "et";
  @SerializedName(SERIALIZED_NAME_ET)
  private BigDecimal et;

  public static final String SERIALIZED_NAME_SV = "sv";
  @SerializedName(SERIALIZED_NAME_SV)
  private BigDecimal sv;

  public static final String SERIALIZED_NAME_TH = "th";
  @SerializedName(SERIALIZED_NAME_TH)
  private BigDecimal th;

  public static final String SERIALIZED_NAME_BS = "bs";
  @SerializedName(SERIALIZED_NAME_BS)
  private BigDecimal bs;

  public static final String SERIALIZED_NAME_DA = "da";
  @SerializedName(SERIALIZED_NAME_DA)
  private BigDecimal da;

  public static final String SERIALIZED_NAME_DE = "de";
  @SerializedName(SERIALIZED_NAME_DE)
  private BigDecimal de;

  public static final String SERIALIZED_NAME_MK = "mk";
  @SerializedName(SERIALIZED_NAME_MK)
  private BigDecimal mk;

  public static final String SERIALIZED_NAME_NO = "no";
  @SerializedName(SERIALIZED_NAME_NO)
  private BigDecimal no;

  public static final String SERIALIZED_NAME_RU = "ru";
  @SerializedName(SERIALIZED_NAME_RU)
  private BigDecimal ru;

  public FeatureEpisodeAttributesSubtitlesCounts() {
  }

  public FeatureEpisodeAttributesSubtitlesCounts pl(BigDecimal pl) {

    this.pl = pl;
    return this;
  }

   /**
   * Get pl
   * @return pl
  **/
  @javax.annotation.Nonnull

  public BigDecimal getPl() {
    return pl;
  }


  public void setPl(BigDecimal pl) {
    this.pl = pl;
  }


  public FeatureEpisodeAttributesSubtitlesCounts en(BigDecimal en) {

    this.en = en;
    return this;
  }

   /**
   * Get en
   * @return en
  **/
  @javax.annotation.Nonnull

  public BigDecimal getEn() {
    return en;
  }


  public void setEn(BigDecimal en) {
    this.en = en;
  }


  public FeatureEpisodeAttributesSubtitlesCounts ptBR(BigDecimal ptBR) {

    this.ptBR = ptBR;
    return this;
  }

   /**
   * Get ptBR
   * @return ptBR
  **/
  @javax.annotation.Nonnull

  public BigDecimal getPtBR() {
    return ptBR;
  }


  public void setPtBR(BigDecimal ptBR) {
    this.ptBR = ptBR;
  }


  public FeatureEpisodeAttributesSubtitlesCounts es(BigDecimal es) {

    this.es = es;
    return this;
  }

   /**
   * Get es
   * @return es
  **/
  @javax.annotation.Nonnull

  public BigDecimal getEs() {
    return es;
  }


  public void setEs(BigDecimal es) {
    this.es = es;
  }


  public FeatureEpisodeAttributesSubtitlesCounts ro(BigDecimal ro) {

    this.ro = ro;
    return this;
  }

   /**
   * Get ro
   * @return ro
  **/
  @javax.annotation.Nonnull

  public BigDecimal getRo() {
    return ro;
  }


  public void setRo(BigDecimal ro) {
    this.ro = ro;
  }


  public FeatureEpisodeAttributesSubtitlesCounts nl(BigDecimal nl) {

    this.nl = nl;
    return this;
  }

   /**
   * Get nl
   * @return nl
  **/
  @javax.annotation.Nonnull

  public BigDecimal getNl() {
    return nl;
  }


  public void setNl(BigDecimal nl) {
    this.nl = nl;
  }


  public FeatureEpisodeAttributesSubtitlesCounts tr(BigDecimal tr) {

    this.tr = tr;
    return this;
  }

   /**
   * Get tr
   * @return tr
  **/
  @javax.annotation.Nonnull

  public BigDecimal getTr() {
    return tr;
  }


  public void setTr(BigDecimal tr) {
    this.tr = tr;
  }


  public FeatureEpisodeAttributesSubtitlesCounts he(BigDecimal he) {

    this.he = he;
    return this;
  }

   /**
   * Get he
   * @return he
  **/
  @javax.annotation.Nonnull

  public BigDecimal getHe() {
    return he;
  }


  public void setHe(BigDecimal he) {
    this.he = he;
  }


  public FeatureEpisodeAttributesSubtitlesCounts ptPT(BigDecimal ptPT) {

    this.ptPT = ptPT;
    return this;
  }

   /**
   * Get ptPT
   * @return ptPT
  **/
  @javax.annotation.Nonnull

  public BigDecimal getPtPT() {
    return ptPT;
  }


  public void setPtPT(BigDecimal ptPT) {
    this.ptPT = ptPT;
  }


  public FeatureEpisodeAttributesSubtitlesCounts cs(BigDecimal cs) {

    this.cs = cs;
    return this;
  }

   /**
   * Get cs
   * @return cs
  **/
  @javax.annotation.Nonnull

  public BigDecimal getCs() {
    return cs;
  }


  public void setCs(BigDecimal cs) {
    this.cs = cs;
  }


  public FeatureEpisodeAttributesSubtitlesCounts fi(BigDecimal fi) {

    this.fi = fi;
    return this;
  }

   /**
   * Get fi
   * @return fi
  **/
  @javax.annotation.Nonnull

  public BigDecimal getFi() {
    return fi;
  }


  public void setFi(BigDecimal fi) {
    this.fi = fi;
  }


  public FeatureEpisodeAttributesSubtitlesCounts hu(BigDecimal hu) {

    this.hu = hu;
    return this;
  }

   /**
   * Get hu
   * @return hu
  **/
  @javax.annotation.Nonnull

  public BigDecimal getHu() {
    return hu;
  }


  public void setHu(BigDecimal hu) {
    this.hu = hu;
  }


  public FeatureEpisodeAttributesSubtitlesCounts ar(BigDecimal ar) {

    this.ar = ar;
    return this;
  }

   /**
   * Get ar
   * @return ar
  **/
  @javax.annotation.Nonnull

  public BigDecimal getAr() {
    return ar;
  }


  public void setAr(BigDecimal ar) {
    this.ar = ar;
  }


  public FeatureEpisodeAttributesSubtitlesCounts bg(BigDecimal bg) {

    this.bg = bg;
    return this;
  }

   /**
   * Get bg
   * @return bg
  **/
  @javax.annotation.Nonnull

  public BigDecimal getBg() {
    return bg;
  }


  public void setBg(BigDecimal bg) {
    this.bg = bg;
  }


  public FeatureEpisodeAttributesSubtitlesCounts fr(BigDecimal fr) {

    this.fr = fr;
    return this;
  }

   /**
   * Get fr
   * @return fr
  **/
  @javax.annotation.Nonnull

  public BigDecimal getFr() {
    return fr;
  }


  public void setFr(BigDecimal fr) {
    this.fr = fr;
  }


  public FeatureEpisodeAttributesSubtitlesCounts sl(BigDecimal sl) {

    this.sl = sl;
    return this;
  }

   /**
   * Get sl
   * @return sl
  **/
  @javax.annotation.Nonnull

  public BigDecimal getSl() {
    return sl;
  }


  public void setSl(BigDecimal sl) {
    this.sl = sl;
  }


  public FeatureEpisodeAttributesSubtitlesCounts el(BigDecimal el) {

    this.el = el;
    return this;
  }

   /**
   * Get el
   * @return el
  **/
  @javax.annotation.Nonnull

  public BigDecimal getEl() {
    return el;
  }


  public void setEl(BigDecimal el) {
    this.el = el;
  }


  public FeatureEpisodeAttributesSubtitlesCounts hr(BigDecimal hr) {

    this.hr = hr;
    return this;
  }

   /**
   * Get hr
   * @return hr
  **/
  @javax.annotation.Nonnull

  public BigDecimal getHr() {
    return hr;
  }


  public void setHr(BigDecimal hr) {
    this.hr = hr;
  }


  public FeatureEpisodeAttributesSubtitlesCounts sr(BigDecimal sr) {

    this.sr = sr;
    return this;
  }

   /**
   * Get sr
   * @return sr
  **/
  @javax.annotation.Nonnull

  public BigDecimal getSr() {
    return sr;
  }


  public void setSr(BigDecimal sr) {
    this.sr = sr;
  }


  public FeatureEpisodeAttributesSubtitlesCounts et(BigDecimal et) {

    this.et = et;
    return this;
  }

   /**
   * Get et
   * @return et
  **/
  @javax.annotation.Nonnull

  public BigDecimal getEt() {
    return et;
  }


  public void setEt(BigDecimal et) {
    this.et = et;
  }


  public FeatureEpisodeAttributesSubtitlesCounts sv(BigDecimal sv) {

    this.sv = sv;
    return this;
  }

   /**
   * Get sv
   * @return sv
  **/
  @javax.annotation.Nonnull

  public BigDecimal getSv() {
    return sv;
  }


  public void setSv(BigDecimal sv) {
    this.sv = sv;
  }


  public FeatureEpisodeAttributesSubtitlesCounts th(BigDecimal th) {

    this.th = th;
    return this;
  }

   /**
   * Get th
   * @return th
  **/
  @javax.annotation.Nonnull

  public BigDecimal getTh() {
    return th;
  }


  public void setTh(BigDecimal th) {
    this.th = th;
  }


  public FeatureEpisodeAttributesSubtitlesCounts bs(BigDecimal bs) {

    this.bs = bs;
    return this;
  }

   /**
   * Get bs
   * @return bs
  **/
  @javax.annotation.Nonnull

  public BigDecimal getBs() {
    return bs;
  }


  public void setBs(BigDecimal bs) {
    this.bs = bs;
  }


  public FeatureEpisodeAttributesSubtitlesCounts da(BigDecimal da) {

    this.da = da;
    return this;
  }

   /**
   * Get da
   * @return da
  **/
  @javax.annotation.Nonnull

  public BigDecimal getDa() {
    return da;
  }


  public void setDa(BigDecimal da) {
    this.da = da;
  }


  public FeatureEpisodeAttributesSubtitlesCounts de(BigDecimal de) {

    this.de = de;
    return this;
  }

   /**
   * Get de
   * @return de
  **/
  @javax.annotation.Nonnull

  public BigDecimal getDe() {
    return de;
  }


  public void setDe(BigDecimal de) {
    this.de = de;
  }


  public FeatureEpisodeAttributesSubtitlesCounts mk(BigDecimal mk) {

    this.mk = mk;
    return this;
  }

   /**
   * Get mk
   * @return mk
  **/
  @javax.annotation.Nonnull

  public BigDecimal getMk() {
    return mk;
  }


  public void setMk(BigDecimal mk) {
    this.mk = mk;
  }


  public FeatureEpisodeAttributesSubtitlesCounts no(BigDecimal no) {

    this.no = no;
    return this;
  }

   /**
   * Get no
   * @return no
  **/
  @javax.annotation.Nonnull

  public BigDecimal getNo() {
    return no;
  }


  public void setNo(BigDecimal no) {
    this.no = no;
  }


  public FeatureEpisodeAttributesSubtitlesCounts ru(BigDecimal ru) {

    this.ru = ru;
    return this;
  }

   /**
   * Get ru
   * @return ru
  **/
  @javax.annotation.Nonnull

  public BigDecimal getRu() {
    return ru;
  }


  public void setRu(BigDecimal ru) {
    this.ru = ru;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeatureEpisodeAttributesSubtitlesCounts featureEpisodeAttributesSubtitlesCounts = (FeatureEpisodeAttributesSubtitlesCounts) o;
    return Objects.equals(this.pl, featureEpisodeAttributesSubtitlesCounts.pl) &&
        Objects.equals(this.en, featureEpisodeAttributesSubtitlesCounts.en) &&
        Objects.equals(this.ptBR, featureEpisodeAttributesSubtitlesCounts.ptBR) &&
        Objects.equals(this.es, featureEpisodeAttributesSubtitlesCounts.es) &&
        Objects.equals(this.ro, featureEpisodeAttributesSubtitlesCounts.ro) &&
        Objects.equals(this.nl, featureEpisodeAttributesSubtitlesCounts.nl) &&
        Objects.equals(this.tr, featureEpisodeAttributesSubtitlesCounts.tr) &&
        Objects.equals(this.he, featureEpisodeAttributesSubtitlesCounts.he) &&
        Objects.equals(this.ptPT, featureEpisodeAttributesSubtitlesCounts.ptPT) &&
        Objects.equals(this.cs, featureEpisodeAttributesSubtitlesCounts.cs) &&
        Objects.equals(this.fi, featureEpisodeAttributesSubtitlesCounts.fi) &&
        Objects.equals(this.hu, featureEpisodeAttributesSubtitlesCounts.hu) &&
        Objects.equals(this.ar, featureEpisodeAttributesSubtitlesCounts.ar) &&
        Objects.equals(this.bg, featureEpisodeAttributesSubtitlesCounts.bg) &&
        Objects.equals(this.fr, featureEpisodeAttributesSubtitlesCounts.fr) &&
        Objects.equals(this.sl, featureEpisodeAttributesSubtitlesCounts.sl) &&
        Objects.equals(this.el, featureEpisodeAttributesSubtitlesCounts.el) &&
        Objects.equals(this.hr, featureEpisodeAttributesSubtitlesCounts.hr) &&
        Objects.equals(this.sr, featureEpisodeAttributesSubtitlesCounts.sr) &&
        Objects.equals(this.et, featureEpisodeAttributesSubtitlesCounts.et) &&
        Objects.equals(this.sv, featureEpisodeAttributesSubtitlesCounts.sv) &&
        Objects.equals(this.th, featureEpisodeAttributesSubtitlesCounts.th) &&
        Objects.equals(this.bs, featureEpisodeAttributesSubtitlesCounts.bs) &&
        Objects.equals(this.da, featureEpisodeAttributesSubtitlesCounts.da) &&
        Objects.equals(this.de, featureEpisodeAttributesSubtitlesCounts.de) &&
        Objects.equals(this.mk, featureEpisodeAttributesSubtitlesCounts.mk) &&
        Objects.equals(this.no, featureEpisodeAttributesSubtitlesCounts.no) &&
        Objects.equals(this.ru, featureEpisodeAttributesSubtitlesCounts.ru);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pl, en, ptBR, es, ro, nl, tr, he, ptPT, cs, fi, hu, ar, bg, fr, sl, el, hr, sr, et, sv, th, bs, da, de, mk, no, ru);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeatureEpisodeAttributesSubtitlesCounts {\n");
    sb.append("    pl: ").append(toIndentedString(pl)).append("\n");
    sb.append("    en: ").append(toIndentedString(en)).append("\n");
    sb.append("    ptBR: ").append(toIndentedString(ptBR)).append("\n");
    sb.append("    es: ").append(toIndentedString(es)).append("\n");
    sb.append("    ro: ").append(toIndentedString(ro)).append("\n");
    sb.append("    nl: ").append(toIndentedString(nl)).append("\n");
    sb.append("    tr: ").append(toIndentedString(tr)).append("\n");
    sb.append("    he: ").append(toIndentedString(he)).append("\n");
    sb.append("    ptPT: ").append(toIndentedString(ptPT)).append("\n");
    sb.append("    cs: ").append(toIndentedString(cs)).append("\n");
    sb.append("    fi: ").append(toIndentedString(fi)).append("\n");
    sb.append("    hu: ").append(toIndentedString(hu)).append("\n");
    sb.append("    ar: ").append(toIndentedString(ar)).append("\n");
    sb.append("    bg: ").append(toIndentedString(bg)).append("\n");
    sb.append("    fr: ").append(toIndentedString(fr)).append("\n");
    sb.append("    sl: ").append(toIndentedString(sl)).append("\n");
    sb.append("    el: ").append(toIndentedString(el)).append("\n");
    sb.append("    hr: ").append(toIndentedString(hr)).append("\n");
    sb.append("    sr: ").append(toIndentedString(sr)).append("\n");
    sb.append("    et: ").append(toIndentedString(et)).append("\n");
    sb.append("    sv: ").append(toIndentedString(sv)).append("\n");
    sb.append("    th: ").append(toIndentedString(th)).append("\n");
    sb.append("    bs: ").append(toIndentedString(bs)).append("\n");
    sb.append("    da: ").append(toIndentedString(da)).append("\n");
    sb.append("    de: ").append(toIndentedString(de)).append("\n");
    sb.append("    mk: ").append(toIndentedString(mk)).append("\n");
    sb.append("    no: ").append(toIndentedString(no)).append("\n");
    sb.append("    ru: ").append(toIndentedString(ru)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

