/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;

/**
 * FeatureMovieAttributesSubtitlesCounts
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-26T20:07:01.076156+02:00[Europe/Amsterdam]")
public class FeatureMovieAttributesSubtitlesCounts {
  public static final String SERIALIZED_NAME_EN = "en";
  @SerializedName(SERIALIZED_NAME_EN)
  private BigDecimal en;

  public static final String SERIALIZED_NAME_PT_P_T = "pt-PT";
  @SerializedName(SERIALIZED_NAME_PT_P_T)
  private BigDecimal ptPT;

  public static final String SERIALIZED_NAME_FI = "fi";
  @SerializedName(SERIALIZED_NAME_FI)
  private BigDecimal fi;

  public static final String SERIALIZED_NAME_PT_B_R = "pt-BR";
  @SerializedName(SERIALIZED_NAME_PT_B_R)
  private BigDecimal ptBR;

  public static final String SERIALIZED_NAME_ES = "es";
  @SerializedName(SERIALIZED_NAME_ES)
  private BigDecimal es;

  public static final String SERIALIZED_NAME_AR = "ar";
  @SerializedName(SERIALIZED_NAME_AR)
  private BigDecimal ar;

  public static final String SERIALIZED_NAME_PL = "pl";
  @SerializedName(SERIALIZED_NAME_PL)
  private BigDecimal pl;

  public static final String SERIALIZED_NAME_SR = "sr";
  @SerializedName(SERIALIZED_NAME_SR)
  private BigDecimal sr;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private BigDecimal id;

  public static final String SERIALIZED_NAME_RO = "ro";
  @SerializedName(SERIALIZED_NAME_RO)
  private BigDecimal ro;

  public static final String SERIALIZED_NAME_ZH_C_N = "zh-CN";
  @SerializedName(SERIALIZED_NAME_ZH_C_N)
  private BigDecimal zhCN;

  public static final String SERIALIZED_NAME_NL = "nl";
  @SerializedName(SERIALIZED_NAME_NL)
  private BigDecimal nl;

  public static final String SERIALIZED_NAME_EL = "el";
  @SerializedName(SERIALIZED_NAME_EL)
  private BigDecimal el;

  public static final String SERIALIZED_NAME_HU = "hu";
  @SerializedName(SERIALIZED_NAME_HU)
  private BigDecimal hu;

  public static final String SERIALIZED_NAME_FR = "fr";
  @SerializedName(SERIALIZED_NAME_FR)
  private BigDecimal fr;

  public static final String SERIALIZED_NAME_SL = "sl";
  @SerializedName(SERIALIZED_NAME_SL)
  private BigDecimal sl;

  public static final String SERIALIZED_NAME_TR = "tr";
  @SerializedName(SERIALIZED_NAME_TR)
  private BigDecimal tr;

  public static final String SERIALIZED_NAME_ET = "et";
  @SerializedName(SERIALIZED_NAME_ET)
  private BigDecimal et;

  public static final String SERIALIZED_NAME_BG = "bg";
  @SerializedName(SERIALIZED_NAME_BG)
  private BigDecimal bg;

  public static final String SERIALIZED_NAME_CS = "cs";
  @SerializedName(SERIALIZED_NAME_CS)
  private BigDecimal cs;

  public static final String SERIALIZED_NAME_DE = "de";
  @SerializedName(SERIALIZED_NAME_DE)
  private BigDecimal de;

  public static final String SERIALIZED_NAME_HE = "he";
  @SerializedName(SERIALIZED_NAME_HE)
  private BigDecimal he;

  public static final String SERIALIZED_NAME_IT = "it";
  @SerializedName(SERIALIZED_NAME_IT)
  private BigDecimal it;

  public static final String SERIALIZED_NAME_VI = "vi";
  @SerializedName(SERIALIZED_NAME_VI)
  private BigDecimal vi;

  public static final String SERIALIZED_NAME_HR = "hr";
  @SerializedName(SERIALIZED_NAME_HR)
  private BigDecimal hr;

  public static final String SERIALIZED_NAME_KO = "ko";
  @SerializedName(SERIALIZED_NAME_KO)
  private BigDecimal ko;

  public static final String SERIALIZED_NAME_NO = "no";
  @SerializedName(SERIALIZED_NAME_NO)
  private BigDecimal no;

  public static final String SERIALIZED_NAME_SV = "sv";
  @SerializedName(SERIALIZED_NAME_SV)
  private BigDecimal sv;

  public static final String SERIALIZED_NAME_TA = "ta";
  @SerializedName(SERIALIZED_NAME_TA)
  private BigDecimal ta;

  public static final String SERIALIZED_NAME_EU = "eu";
  @SerializedName(SERIALIZED_NAME_EU)
  private BigDecimal eu;

  public static final String SERIALIZED_NAME_DA = "da";
  @SerializedName(SERIALIZED_NAME_DA)
  private BigDecimal da;

  public static final String SERIALIZED_NAME_FA = "fa";
  @SerializedName(SERIALIZED_NAME_FA)
  private BigDecimal fa;

  public static final String SERIALIZED_NAME_SK = "sk";
  @SerializedName(SERIALIZED_NAME_SK)
  private BigDecimal sk;

  public static final String SERIALIZED_NAME_UK = "uk";
  @SerializedName(SERIALIZED_NAME_UK)
  private BigDecimal uk;

  public static final String SERIALIZED_NAME_ZH_T_W = "zh-TW";
  @SerializedName(SERIALIZED_NAME_ZH_T_W)
  private BigDecimal zhTW;

  public static final String SERIALIZED_NAME_BN = "bn";
  @SerializedName(SERIALIZED_NAME_BN)
  private BigDecimal bn;

  public static final String SERIALIZED_NAME_KA = "ka";
  @SerializedName(SERIALIZED_NAME_KA)
  private BigDecimal ka;

  public static final String SERIALIZED_NAME_JA = "ja";
  @SerializedName(SERIALIZED_NAME_JA)
  private BigDecimal ja;

  public static final String SERIALIZED_NAME_LT = "lt";
  @SerializedName(SERIALIZED_NAME_LT)
  private BigDecimal lt;

  public static final String SERIALIZED_NAME_MK = "mk";
  @SerializedName(SERIALIZED_NAME_MK)
  private BigDecimal mk;

  public static final String SERIALIZED_NAME_ML = "ml";
  @SerializedName(SERIALIZED_NAME_ML)
  private BigDecimal ml;

  public static final String SERIALIZED_NAME_MS = "ms";
  @SerializedName(SERIALIZED_NAME_MS)
  private BigDecimal ms;

  public static final String SERIALIZED_NAME_RU = "ru";
  @SerializedName(SERIALIZED_NAME_RU)
  private BigDecimal ru;

  public static final String SERIALIZED_NAME_ZE = "ze";
  @SerializedName(SERIALIZED_NAME_ZE)
  private BigDecimal ze;

  public FeatureMovieAttributesSubtitlesCounts() {
  }

  public FeatureMovieAttributesSubtitlesCounts en(BigDecimal en) {

    this.en = en;
    return this;
  }

   /**
   * Get en
   * @return en
  **/
  @javax.annotation.Nonnull

  public BigDecimal getEn() {
    return en;
  }


  public void setEn(BigDecimal en) {
    this.en = en;
  }


  public FeatureMovieAttributesSubtitlesCounts ptPT(BigDecimal ptPT) {

    this.ptPT = ptPT;
    return this;
  }

   /**
   * Get ptPT
   * @return ptPT
  **/
  @javax.annotation.Nonnull

  public BigDecimal getPtPT() {
    return ptPT;
  }


  public void setPtPT(BigDecimal ptPT) {
    this.ptPT = ptPT;
  }


  public FeatureMovieAttributesSubtitlesCounts fi(BigDecimal fi) {

    this.fi = fi;
    return this;
  }

   /**
   * Get fi
   * @return fi
  **/
  @javax.annotation.Nonnull

  public BigDecimal getFi() {
    return fi;
  }


  public void setFi(BigDecimal fi) {
    this.fi = fi;
  }


  public FeatureMovieAttributesSubtitlesCounts ptBR(BigDecimal ptBR) {

    this.ptBR = ptBR;
    return this;
  }

   /**
   * Get ptBR
   * @return ptBR
  **/
  @javax.annotation.Nonnull

  public BigDecimal getPtBR() {
    return ptBR;
  }


  public void setPtBR(BigDecimal ptBR) {
    this.ptBR = ptBR;
  }


  public FeatureMovieAttributesSubtitlesCounts es(BigDecimal es) {

    this.es = es;
    return this;
  }

   /**
   * Get es
   * @return es
  **/
  @javax.annotation.Nonnull

  public BigDecimal getEs() {
    return es;
  }


  public void setEs(BigDecimal es) {
    this.es = es;
  }


  public FeatureMovieAttributesSubtitlesCounts ar(BigDecimal ar) {

    this.ar = ar;
    return this;
  }

   /**
   * Get ar
   * @return ar
  **/
  @javax.annotation.Nonnull

  public BigDecimal getAr() {
    return ar;
  }


  public void setAr(BigDecimal ar) {
    this.ar = ar;
  }


  public FeatureMovieAttributesSubtitlesCounts pl(BigDecimal pl) {

    this.pl = pl;
    return this;
  }

   /**
   * Get pl
   * @return pl
  **/
  @javax.annotation.Nonnull

  public BigDecimal getPl() {
    return pl;
  }


  public void setPl(BigDecimal pl) {
    this.pl = pl;
  }


  public FeatureMovieAttributesSubtitlesCounts sr(BigDecimal sr) {

    this.sr = sr;
    return this;
  }

   /**
   * Get sr
   * @return sr
  **/
  @javax.annotation.Nonnull

  public BigDecimal getSr() {
    return sr;
  }


  public void setSr(BigDecimal sr) {
    this.sr = sr;
  }


  public FeatureMovieAttributesSubtitlesCounts id(BigDecimal id) {

    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull

  public BigDecimal getId() {
    return id;
  }


  public void setId(BigDecimal id) {
    this.id = id;
  }


  public FeatureMovieAttributesSubtitlesCounts ro(BigDecimal ro) {

    this.ro = ro;
    return this;
  }

   /**
   * Get ro
   * @return ro
  **/
  @javax.annotation.Nonnull

  public BigDecimal getRo() {
    return ro;
  }


  public void setRo(BigDecimal ro) {
    this.ro = ro;
  }


  public FeatureMovieAttributesSubtitlesCounts zhCN(BigDecimal zhCN) {

    this.zhCN = zhCN;
    return this;
  }

   /**
   * Get zhCN
   * @return zhCN
  **/
  @javax.annotation.Nonnull

  public BigDecimal getZhCN() {
    return zhCN;
  }


  public void setZhCN(BigDecimal zhCN) {
    this.zhCN = zhCN;
  }


  public FeatureMovieAttributesSubtitlesCounts nl(BigDecimal nl) {

    this.nl = nl;
    return this;
  }

   /**
   * Get nl
   * @return nl
  **/
  @javax.annotation.Nonnull

  public BigDecimal getNl() {
    return nl;
  }


  public void setNl(BigDecimal nl) {
    this.nl = nl;
  }


  public FeatureMovieAttributesSubtitlesCounts el(BigDecimal el) {

    this.el = el;
    return this;
  }

   /**
   * Get el
   * @return el
  **/
  @javax.annotation.Nonnull

  public BigDecimal getEl() {
    return el;
  }


  public void setEl(BigDecimal el) {
    this.el = el;
  }


  public FeatureMovieAttributesSubtitlesCounts hu(BigDecimal hu) {

    this.hu = hu;
    return this;
  }

   /**
   * Get hu
   * @return hu
  **/
  @javax.annotation.Nonnull

  public BigDecimal getHu() {
    return hu;
  }


  public void setHu(BigDecimal hu) {
    this.hu = hu;
  }


  public FeatureMovieAttributesSubtitlesCounts fr(BigDecimal fr) {

    this.fr = fr;
    return this;
  }

   /**
   * Get fr
   * @return fr
  **/
  @javax.annotation.Nonnull

  public BigDecimal getFr() {
    return fr;
  }


  public void setFr(BigDecimal fr) {
    this.fr = fr;
  }


  public FeatureMovieAttributesSubtitlesCounts sl(BigDecimal sl) {

    this.sl = sl;
    return this;
  }

   /**
   * Get sl
   * @return sl
  **/
  @javax.annotation.Nonnull

  public BigDecimal getSl() {
    return sl;
  }


  public void setSl(BigDecimal sl) {
    this.sl = sl;
  }


  public FeatureMovieAttributesSubtitlesCounts tr(BigDecimal tr) {

    this.tr = tr;
    return this;
  }

   /**
   * Get tr
   * @return tr
  **/
  @javax.annotation.Nonnull

  public BigDecimal getTr() {
    return tr;
  }


  public void setTr(BigDecimal tr) {
    this.tr = tr;
  }


  public FeatureMovieAttributesSubtitlesCounts et(BigDecimal et) {

    this.et = et;
    return this;
  }

   /**
   * Get et
   * @return et
  **/
  @javax.annotation.Nonnull

  public BigDecimal getEt() {
    return et;
  }


  public void setEt(BigDecimal et) {
    this.et = et;
  }


  public FeatureMovieAttributesSubtitlesCounts bg(BigDecimal bg) {

    this.bg = bg;
    return this;
  }

   /**
   * Get bg
   * @return bg
  **/
  @javax.annotation.Nonnull

  public BigDecimal getBg() {
    return bg;
  }


  public void setBg(BigDecimal bg) {
    this.bg = bg;
  }


  public FeatureMovieAttributesSubtitlesCounts cs(BigDecimal cs) {

    this.cs = cs;
    return this;
  }

   /**
   * Get cs
   * @return cs
  **/
  @javax.annotation.Nonnull

  public BigDecimal getCs() {
    return cs;
  }


  public void setCs(BigDecimal cs) {
    this.cs = cs;
  }


  public FeatureMovieAttributesSubtitlesCounts de(BigDecimal de) {

    this.de = de;
    return this;
  }

   /**
   * Get de
   * @return de
  **/
  @javax.annotation.Nonnull

  public BigDecimal getDe() {
    return de;
  }


  public void setDe(BigDecimal de) {
    this.de = de;
  }


  public FeatureMovieAttributesSubtitlesCounts he(BigDecimal he) {

    this.he = he;
    return this;
  }

   /**
   * Get he
   * @return he
  **/
  @javax.annotation.Nonnull

  public BigDecimal getHe() {
    return he;
  }


  public void setHe(BigDecimal he) {
    this.he = he;
  }


  public FeatureMovieAttributesSubtitlesCounts it(BigDecimal it) {

    this.it = it;
    return this;
  }

   /**
   * Get it
   * @return it
  **/
  @javax.annotation.Nonnull

  public BigDecimal getIt() {
    return it;
  }


  public void setIt(BigDecimal it) {
    this.it = it;
  }


  public FeatureMovieAttributesSubtitlesCounts vi(BigDecimal vi) {

    this.vi = vi;
    return this;
  }

   /**
   * Get vi
   * @return vi
  **/
  @javax.annotation.Nonnull

  public BigDecimal getVi() {
    return vi;
  }


  public void setVi(BigDecimal vi) {
    this.vi = vi;
  }


  public FeatureMovieAttributesSubtitlesCounts hr(BigDecimal hr) {

    this.hr = hr;
    return this;
  }

   /**
   * Get hr
   * @return hr
  **/
  @javax.annotation.Nonnull

  public BigDecimal getHr() {
    return hr;
  }


  public void setHr(BigDecimal hr) {
    this.hr = hr;
  }


  public FeatureMovieAttributesSubtitlesCounts ko(BigDecimal ko) {

    this.ko = ko;
    return this;
  }

   /**
   * Get ko
   * @return ko
  **/
  @javax.annotation.Nonnull

  public BigDecimal getKo() {
    return ko;
  }


  public void setKo(BigDecimal ko) {
    this.ko = ko;
  }


  public FeatureMovieAttributesSubtitlesCounts no(BigDecimal no) {

    this.no = no;
    return this;
  }

   /**
   * Get no
   * @return no
  **/
  @javax.annotation.Nonnull

  public BigDecimal getNo() {
    return no;
  }


  public void setNo(BigDecimal no) {
    this.no = no;
  }


  public FeatureMovieAttributesSubtitlesCounts sv(BigDecimal sv) {

    this.sv = sv;
    return this;
  }

   /**
   * Get sv
   * @return sv
  **/
  @javax.annotation.Nonnull

  public BigDecimal getSv() {
    return sv;
  }


  public void setSv(BigDecimal sv) {
    this.sv = sv;
  }


  public FeatureMovieAttributesSubtitlesCounts ta(BigDecimal ta) {

    this.ta = ta;
    return this;
  }

   /**
   * Get ta
   * @return ta
  **/
  @javax.annotation.Nonnull

  public BigDecimal getTa() {
    return ta;
  }


  public void setTa(BigDecimal ta) {
    this.ta = ta;
  }


  public FeatureMovieAttributesSubtitlesCounts eu(BigDecimal eu) {

    this.eu = eu;
    return this;
  }

   /**
   * Get eu
   * @return eu
  **/
  @javax.annotation.Nonnull

  public BigDecimal getEu() {
    return eu;
  }


  public void setEu(BigDecimal eu) {
    this.eu = eu;
  }


  public FeatureMovieAttributesSubtitlesCounts da(BigDecimal da) {

    this.da = da;
    return this;
  }

   /**
   * Get da
   * @return da
  **/
  @javax.annotation.Nonnull

  public BigDecimal getDa() {
    return da;
  }


  public void setDa(BigDecimal da) {
    this.da = da;
  }


  public FeatureMovieAttributesSubtitlesCounts fa(BigDecimal fa) {

    this.fa = fa;
    return this;
  }

   /**
   * Get fa
   * @return fa
  **/
  @javax.annotation.Nonnull

  public BigDecimal getFa() {
    return fa;
  }


  public void setFa(BigDecimal fa) {
    this.fa = fa;
  }


  public FeatureMovieAttributesSubtitlesCounts sk(BigDecimal sk) {

    this.sk = sk;
    return this;
  }

   /**
   * Get sk
   * @return sk
  **/
  @javax.annotation.Nonnull

  public BigDecimal getSk() {
    return sk;
  }


  public void setSk(BigDecimal sk) {
    this.sk = sk;
  }


  public FeatureMovieAttributesSubtitlesCounts uk(BigDecimal uk) {

    this.uk = uk;
    return this;
  }

   /**
   * Get uk
   * @return uk
  **/
  @javax.annotation.Nonnull

  public BigDecimal getUk() {
    return uk;
  }


  public void setUk(BigDecimal uk) {
    this.uk = uk;
  }


  public FeatureMovieAttributesSubtitlesCounts zhTW(BigDecimal zhTW) {

    this.zhTW = zhTW;
    return this;
  }

   /**
   * Get zhTW
   * @return zhTW
  **/
  @javax.annotation.Nonnull

  public BigDecimal getZhTW() {
    return zhTW;
  }


  public void setZhTW(BigDecimal zhTW) {
    this.zhTW = zhTW;
  }


  public FeatureMovieAttributesSubtitlesCounts bn(BigDecimal bn) {

    this.bn = bn;
    return this;
  }

   /**
   * Get bn
   * @return bn
  **/
  @javax.annotation.Nonnull

  public BigDecimal getBn() {
    return bn;
  }


  public void setBn(BigDecimal bn) {
    this.bn = bn;
  }


  public FeatureMovieAttributesSubtitlesCounts ka(BigDecimal ka) {

    this.ka = ka;
    return this;
  }

   /**
   * Get ka
   * @return ka
  **/
  @javax.annotation.Nonnull

  public BigDecimal getKa() {
    return ka;
  }


  public void setKa(BigDecimal ka) {
    this.ka = ka;
  }


  public FeatureMovieAttributesSubtitlesCounts ja(BigDecimal ja) {

    this.ja = ja;
    return this;
  }

   /**
   * Get ja
   * @return ja
  **/
  @javax.annotation.Nonnull

  public BigDecimal getJa() {
    return ja;
  }


  public void setJa(BigDecimal ja) {
    this.ja = ja;
  }


  public FeatureMovieAttributesSubtitlesCounts lt(BigDecimal lt) {

    this.lt = lt;
    return this;
  }

   /**
   * Get lt
   * @return lt
  **/
  @javax.annotation.Nonnull

  public BigDecimal getLt() {
    return lt;
  }


  public void setLt(BigDecimal lt) {
    this.lt = lt;
  }


  public FeatureMovieAttributesSubtitlesCounts mk(BigDecimal mk) {

    this.mk = mk;
    return this;
  }

   /**
   * Get mk
   * @return mk
  **/
  @javax.annotation.Nonnull

  public BigDecimal getMk() {
    return mk;
  }


  public void setMk(BigDecimal mk) {
    this.mk = mk;
  }


  public FeatureMovieAttributesSubtitlesCounts ml(BigDecimal ml) {

    this.ml = ml;
    return this;
  }

   /**
   * Get ml
   * @return ml
  **/
  @javax.annotation.Nonnull

  public BigDecimal getMl() {
    return ml;
  }


  public void setMl(BigDecimal ml) {
    this.ml = ml;
  }


  public FeatureMovieAttributesSubtitlesCounts ms(BigDecimal ms) {

    this.ms = ms;
    return this;
  }

   /**
   * Get ms
   * @return ms
  **/
  @javax.annotation.Nonnull

  public BigDecimal getMs() {
    return ms;
  }


  public void setMs(BigDecimal ms) {
    this.ms = ms;
  }


  public FeatureMovieAttributesSubtitlesCounts ru(BigDecimal ru) {

    this.ru = ru;
    return this;
  }

   /**
   * Get ru
   * @return ru
  **/
  @javax.annotation.Nonnull

  public BigDecimal getRu() {
    return ru;
  }


  public void setRu(BigDecimal ru) {
    this.ru = ru;
  }


  public FeatureMovieAttributesSubtitlesCounts ze(BigDecimal ze) {

    this.ze = ze;
    return this;
  }

   /**
   * Get ze
   * @return ze
  **/
  @javax.annotation.Nonnull

  public BigDecimal getZe() {
    return ze;
  }


  public void setZe(BigDecimal ze) {
    this.ze = ze;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeatureMovieAttributesSubtitlesCounts featureMovieAttributesSubtitlesCounts = (FeatureMovieAttributesSubtitlesCounts) o;
    return Objects.equals(this.en, featureMovieAttributesSubtitlesCounts.en) &&
        Objects.equals(this.ptPT, featureMovieAttributesSubtitlesCounts.ptPT) &&
        Objects.equals(this.fi, featureMovieAttributesSubtitlesCounts.fi) &&
        Objects.equals(this.ptBR, featureMovieAttributesSubtitlesCounts.ptBR) &&
        Objects.equals(this.es, featureMovieAttributesSubtitlesCounts.es) &&
        Objects.equals(this.ar, featureMovieAttributesSubtitlesCounts.ar) &&
        Objects.equals(this.pl, featureMovieAttributesSubtitlesCounts.pl) &&
        Objects.equals(this.sr, featureMovieAttributesSubtitlesCounts.sr) &&
        Objects.equals(this.id, featureMovieAttributesSubtitlesCounts.id) &&
        Objects.equals(this.ro, featureMovieAttributesSubtitlesCounts.ro) &&
        Objects.equals(this.zhCN, featureMovieAttributesSubtitlesCounts.zhCN) &&
        Objects.equals(this.nl, featureMovieAttributesSubtitlesCounts.nl) &&
        Objects.equals(this.el, featureMovieAttributesSubtitlesCounts.el) &&
        Objects.equals(this.hu, featureMovieAttributesSubtitlesCounts.hu) &&
        Objects.equals(this.fr, featureMovieAttributesSubtitlesCounts.fr) &&
        Objects.equals(this.sl, featureMovieAttributesSubtitlesCounts.sl) &&
        Objects.equals(this.tr, featureMovieAttributesSubtitlesCounts.tr) &&
        Objects.equals(this.et, featureMovieAttributesSubtitlesCounts.et) &&
        Objects.equals(this.bg, featureMovieAttributesSubtitlesCounts.bg) &&
        Objects.equals(this.cs, featureMovieAttributesSubtitlesCounts.cs) &&
        Objects.equals(this.de, featureMovieAttributesSubtitlesCounts.de) &&
        Objects.equals(this.he, featureMovieAttributesSubtitlesCounts.he) &&
        Objects.equals(this.it, featureMovieAttributesSubtitlesCounts.it) &&
        Objects.equals(this.vi, featureMovieAttributesSubtitlesCounts.vi) &&
        Objects.equals(this.hr, featureMovieAttributesSubtitlesCounts.hr) &&
        Objects.equals(this.ko, featureMovieAttributesSubtitlesCounts.ko) &&
        Objects.equals(this.no, featureMovieAttributesSubtitlesCounts.no) &&
        Objects.equals(this.sv, featureMovieAttributesSubtitlesCounts.sv) &&
        Objects.equals(this.ta, featureMovieAttributesSubtitlesCounts.ta) &&
        Objects.equals(this.eu, featureMovieAttributesSubtitlesCounts.eu) &&
        Objects.equals(this.da, featureMovieAttributesSubtitlesCounts.da) &&
        Objects.equals(this.fa, featureMovieAttributesSubtitlesCounts.fa) &&
        Objects.equals(this.sk, featureMovieAttributesSubtitlesCounts.sk) &&
        Objects.equals(this.uk, featureMovieAttributesSubtitlesCounts.uk) &&
        Objects.equals(this.zhTW, featureMovieAttributesSubtitlesCounts.zhTW) &&
        Objects.equals(this.bn, featureMovieAttributesSubtitlesCounts.bn) &&
        Objects.equals(this.ka, featureMovieAttributesSubtitlesCounts.ka) &&
        Objects.equals(this.ja, featureMovieAttributesSubtitlesCounts.ja) &&
        Objects.equals(this.lt, featureMovieAttributesSubtitlesCounts.lt) &&
        Objects.equals(this.mk, featureMovieAttributesSubtitlesCounts.mk) &&
        Objects.equals(this.ml, featureMovieAttributesSubtitlesCounts.ml) &&
        Objects.equals(this.ms, featureMovieAttributesSubtitlesCounts.ms) &&
        Objects.equals(this.ru, featureMovieAttributesSubtitlesCounts.ru) &&
        Objects.equals(this.ze, featureMovieAttributesSubtitlesCounts.ze);
  }

  @Override
  public int hashCode() {
    return Objects.hash(en, ptPT, fi, ptBR, es, ar, pl, sr, id, ro, zhCN, nl, el, hu, fr, sl, tr, et, bg, cs, de, he, it, vi, hr, ko, no, sv, ta, eu, da, fa, sk, uk, zhTW, bn, ka, ja, lt, mk, ml, ms, ru, ze);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeatureMovieAttributesSubtitlesCounts {\n");
    sb.append("    en: ").append(toIndentedString(en)).append("\n");
    sb.append("    ptPT: ").append(toIndentedString(ptPT)).append("\n");
    sb.append("    fi: ").append(toIndentedString(fi)).append("\n");
    sb.append("    ptBR: ").append(toIndentedString(ptBR)).append("\n");
    sb.append("    es: ").append(toIndentedString(es)).append("\n");
    sb.append("    ar: ").append(toIndentedString(ar)).append("\n");
    sb.append("    pl: ").append(toIndentedString(pl)).append("\n");
    sb.append("    sr: ").append(toIndentedString(sr)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ro: ").append(toIndentedString(ro)).append("\n");
    sb.append("    zhCN: ").append(toIndentedString(zhCN)).append("\n");
    sb.append("    nl: ").append(toIndentedString(nl)).append("\n");
    sb.append("    el: ").append(toIndentedString(el)).append("\n");
    sb.append("    hu: ").append(toIndentedString(hu)).append("\n");
    sb.append("    fr: ").append(toIndentedString(fr)).append("\n");
    sb.append("    sl: ").append(toIndentedString(sl)).append("\n");
    sb.append("    tr: ").append(toIndentedString(tr)).append("\n");
    sb.append("    et: ").append(toIndentedString(et)).append("\n");
    sb.append("    bg: ").append(toIndentedString(bg)).append("\n");
    sb.append("    cs: ").append(toIndentedString(cs)).append("\n");
    sb.append("    de: ").append(toIndentedString(de)).append("\n");
    sb.append("    he: ").append(toIndentedString(he)).append("\n");
    sb.append("    it: ").append(toIndentedString(it)).append("\n");
    sb.append("    vi: ").append(toIndentedString(vi)).append("\n");
    sb.append("    hr: ").append(toIndentedString(hr)).append("\n");
    sb.append("    ko: ").append(toIndentedString(ko)).append("\n");
    sb.append("    no: ").append(toIndentedString(no)).append("\n");
    sb.append("    sv: ").append(toIndentedString(sv)).append("\n");
    sb.append("    ta: ").append(toIndentedString(ta)).append("\n");
    sb.append("    eu: ").append(toIndentedString(eu)).append("\n");
    sb.append("    da: ").append(toIndentedString(da)).append("\n");
    sb.append("    fa: ").append(toIndentedString(fa)).append("\n");
    sb.append("    sk: ").append(toIndentedString(sk)).append("\n");
    sb.append("    uk: ").append(toIndentedString(uk)).append("\n");
    sb.append("    zhTW: ").append(toIndentedString(zhTW)).append("\n");
    sb.append("    bn: ").append(toIndentedString(bn)).append("\n");
    sb.append("    ka: ").append(toIndentedString(ka)).append("\n");
    sb.append("    ja: ").append(toIndentedString(ja)).append("\n");
    sb.append("    lt: ").append(toIndentedString(lt)).append("\n");
    sb.append("    mk: ").append(toIndentedString(mk)).append("\n");
    sb.append("    ml: ").append(toIndentedString(ml)).append("\n");
    sb.append("    ms: ").append(toIndentedString(ms)).append("\n");
    sb.append("    ru: ").append(toIndentedString(ru)).append("\n");
    sb.append("    ze: ").append(toIndentedString(ze)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

