/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;

/**
 *
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-26T20:07:01.076156+02:00[Europe/Amsterdam]")
public class Guessit200Response {
  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_YEAR = "year";
  @SerializedName(SERIALIZED_NAME_YEAR)
  private BigDecimal year;

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  private String language;

  public static final String SERIALIZED_NAME_SUBTITLE_LANGUAGE = "subtitle_language";
  @SerializedName(SERIALIZED_NAME_SUBTITLE_LANGUAGE)
  private String subtitleLanguage;

  public static final String SERIALIZED_NAME_SCREEN_SIZE = "screen_size";
  @SerializedName(SERIALIZED_NAME_SCREEN_SIZE)
  private String screenSize;

  public static final String SERIALIZED_NAME_STREAMING_SERVICE = "streaming_service";
  @SerializedName(SERIALIZED_NAME_STREAMING_SERVICE)
  private String streamingService;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  private String source;

  public static final String SERIALIZED_NAME_OTHER = "other";
  @SerializedName(SERIALIZED_NAME_OTHER)
  private String other;

  public static final String SERIALIZED_NAME_AUDIO_CODEC = "audio_codec";
  @SerializedName(SERIALIZED_NAME_AUDIO_CODEC)
  private String audioCodec;

  public static final String SERIALIZED_NAME_AUDIO_CHANNELS = "audio_channels";
  @SerializedName(SERIALIZED_NAME_AUDIO_CHANNELS)
  private String audioChannels;

  public static final String SERIALIZED_NAME_VIDEO_CODEC = "video_codec";
  @SerializedName(SERIALIZED_NAME_VIDEO_CODEC)
  private String videoCodec;

  public static final String SERIALIZED_NAME_RELEASE_GROUP = "release_group";
  @SerializedName(SERIALIZED_NAME_RELEASE_GROUP)
  private String releaseGroup;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public Guessit200Response() {
  }

  public Guessit200Response title(String title) {

    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nonnull

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public Guessit200Response year(BigDecimal year) {

    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @javax.annotation.Nonnull

  public BigDecimal getYear() {
    return year;
  }


  public void setYear(BigDecimal year) {
    this.year = year;
  }


  public Guessit200Response language(String language) {

    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @javax.annotation.Nonnull

  public String getLanguage() {
    return language;
  }


  public void setLanguage(String language) {
    this.language = language;
  }


  public Guessit200Response subtitleLanguage(String subtitleLanguage) {

    this.subtitleLanguage = subtitleLanguage;
    return this;
  }

   /**
   * Get subtitleLanguage
   * @return subtitleLanguage
  **/
  @javax.annotation.Nonnull

  public String getSubtitleLanguage() {
    return subtitleLanguage;
  }


  public void setSubtitleLanguage(String subtitleLanguage) {
    this.subtitleLanguage = subtitleLanguage;
  }


  public Guessit200Response screenSize(String screenSize) {

    this.screenSize = screenSize;
    return this;
  }

   /**
   * Get screenSize
   * @return screenSize
  **/
  @javax.annotation.Nonnull

  public String getScreenSize() {
    return screenSize;
  }


  public void setScreenSize(String screenSize) {
    this.screenSize = screenSize;
  }


  public Guessit200Response streamingService(String streamingService) {

    this.streamingService = streamingService;
    return this;
  }

   /**
   * Get streamingService
   * @return streamingService
  **/
  @javax.annotation.Nonnull

  public String getStreamingService() {
    return streamingService;
  }


  public void setStreamingService(String streamingService) {
    this.streamingService = streamingService;
  }


  public Guessit200Response source(String source) {

    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @javax.annotation.Nonnull

  public String getSource() {
    return source;
  }


  public void setSource(String source) {
    this.source = source;
  }


  public Guessit200Response other(String other) {

    this.other = other;
    return this;
  }

   /**
   * Get other
   * @return other
  **/
  @javax.annotation.Nonnull

  public String getOther() {
    return other;
  }


  public void setOther(String other) {
    this.other = other;
  }


  public Guessit200Response audioCodec(String audioCodec) {

    this.audioCodec = audioCodec;
    return this;
  }

   /**
   * Get audioCodec
   * @return audioCodec
  **/
  @javax.annotation.Nonnull

  public String getAudioCodec() {
    return audioCodec;
  }


  public void setAudioCodec(String audioCodec) {
    this.audioCodec = audioCodec;
  }


  public Guessit200Response audioChannels(String audioChannels) {

    this.audioChannels = audioChannels;
    return this;
  }

   /**
   * Get audioChannels
   * @return audioChannels
  **/
  @javax.annotation.Nonnull

  public String getAudioChannels() {
    return audioChannels;
  }


  public void setAudioChannels(String audioChannels) {
    this.audioChannels = audioChannels;
  }


  public Guessit200Response videoCodec(String videoCodec) {

    this.videoCodec = videoCodec;
    return this;
  }

   /**
   * Get videoCodec
   * @return videoCodec
  **/
  @javax.annotation.Nonnull

  public String getVideoCodec() {
    return videoCodec;
  }


  public void setVideoCodec(String videoCodec) {
    this.videoCodec = videoCodec;
  }


  public Guessit200Response releaseGroup(String releaseGroup) {

    this.releaseGroup = releaseGroup;
    return this;
  }

   /**
   * Get releaseGroup
   * @return releaseGroup
  **/
  @javax.annotation.Nonnull

  public String getReleaseGroup() {
    return releaseGroup;
  }


  public void setReleaseGroup(String releaseGroup) {
    this.releaseGroup = releaseGroup;
  }


  public Guessit200Response type(String type) {

    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nonnull

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Guessit200Response guessit200Response = (Guessit200Response) o;
    return Objects.equals(this.title, guessit200Response.title) &&
        Objects.equals(this.year, guessit200Response.year) &&
        Objects.equals(this.language, guessit200Response.language) &&
        Objects.equals(this.subtitleLanguage, guessit200Response.subtitleLanguage) &&
        Objects.equals(this.screenSize, guessit200Response.screenSize) &&
        Objects.equals(this.streamingService, guessit200Response.streamingService) &&
        Objects.equals(this.source, guessit200Response.source) &&
        Objects.equals(this.other, guessit200Response.other) &&
        Objects.equals(this.audioCodec, guessit200Response.audioCodec) &&
        Objects.equals(this.audioChannels, guessit200Response.audioChannels) &&
        Objects.equals(this.videoCodec, guessit200Response.videoCodec) &&
        Objects.equals(this.releaseGroup, guessit200Response.releaseGroup) &&
        Objects.equals(this.type, guessit200Response.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, year, language, subtitleLanguage, screenSize, streamingService, source, other, audioCodec, audioChannels, videoCodec, releaseGroup, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Guessit200Response {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    subtitleLanguage: ").append(toIndentedString(subtitleLanguage)).append("\n");
    sb.append("    screenSize: ").append(toIndentedString(screenSize)).append("\n");
    sb.append("    streamingService: ").append(toIndentedString(streamingService)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    other: ").append(toIndentedString(other)).append("\n");
    sb.append("    audioCodec: ").append(toIndentedString(audioCodec)).append("\n");
    sb.append("    audioChannels: ").append(toIndentedString(audioChannels)).append("\n");
    sb.append("    videoCodec: ").append(toIndentedString(videoCodec)).append("\n");
    sb.append("    releaseGroup: ").append(toIndentedString(releaseGroup)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

