/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nl.giejay.subtitles.opensubtitles.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;

/**
 * Userinfo200ResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-26T20:07:01.076156+02:00[Europe/Amsterdam]")
public class Userinfo200ResponseData {
  public static final String SERIALIZED_NAME_ALLOWED_DOWNLOADS = "allowed_downloads";
  @SerializedName(SERIALIZED_NAME_ALLOWED_DOWNLOADS)
  private BigDecimal allowedDownloads;

  public static final String SERIALIZED_NAME_LEVEL = "level";
  @SerializedName(SERIALIZED_NAME_LEVEL)
  private String level;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private BigDecimal userId;

  public static final String SERIALIZED_NAME_EXT_INSTALLED = "ext_installed";
  @SerializedName(SERIALIZED_NAME_EXT_INSTALLED)
  private Boolean extInstalled;

  public static final String SERIALIZED_NAME_VIP = "vip";
  @SerializedName(SERIALIZED_NAME_VIP)
  private Boolean vip;

  public static final String SERIALIZED_NAME_DOWNLOADS_COUNT = "downloads_count";
  @SerializedName(SERIALIZED_NAME_DOWNLOADS_COUNT)
  private BigDecimal downloadsCount;

  public static final String SERIALIZED_NAME_REMAINING_DOWNLOADS = "remaining_downloads";
  @SerializedName(SERIALIZED_NAME_REMAINING_DOWNLOADS)
  private BigDecimal remainingDownloads;

  public Userinfo200ResponseData() {
  }

  public Userinfo200ResponseData allowedDownloads(BigDecimal allowedDownloads) {

    this.allowedDownloads = allowedDownloads;
    return this;
  }

   /**
   * Get allowedDownloads
   * @return allowedDownloads
  **/
  @javax.annotation.Nonnull

  public BigDecimal getAllowedDownloads() {
    return allowedDownloads;
  }


  public void setAllowedDownloads(BigDecimal allowedDownloads) {
    this.allowedDownloads = allowedDownloads;
  }


  public Userinfo200ResponseData level(String level) {

    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  @javax.annotation.Nonnull

  public String getLevel() {
    return level;
  }


  public void setLevel(String level) {
    this.level = level;
  }


  public Userinfo200ResponseData userId(BigDecimal userId) {

    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nonnull

  public BigDecimal getUserId() {
    return userId;
  }


  public void setUserId(BigDecimal userId) {
    this.userId = userId;
  }


  public Userinfo200ResponseData extInstalled(Boolean extInstalled) {

    this.extInstalled = extInstalled;
    return this;
  }

   /**
   * Get extInstalled
   * @return extInstalled
  **/
  @javax.annotation.Nonnull

  public Boolean getExtInstalled() {
    return extInstalled;
  }


  public void setExtInstalled(Boolean extInstalled) {
    this.extInstalled = extInstalled;
  }


  public Userinfo200ResponseData vip(Boolean vip) {

    this.vip = vip;
    return this;
  }

   /**
   * Get vip
   * @return vip
  **/
  @javax.annotation.Nonnull

  public Boolean getVip() {
    return vip;
  }


  public void setVip(Boolean vip) {
    this.vip = vip;
  }


  public Userinfo200ResponseData downloadsCount(BigDecimal downloadsCount) {

    this.downloadsCount = downloadsCount;
    return this;
  }

   /**
   * Get downloadsCount
   * @return downloadsCount
  **/
  @javax.annotation.Nonnull

  public BigDecimal getDownloadsCount() {
    return downloadsCount;
  }


  public void setDownloadsCount(BigDecimal downloadsCount) {
    this.downloadsCount = downloadsCount;
  }


  public Userinfo200ResponseData remainingDownloads(BigDecimal remainingDownloads) {

    this.remainingDownloads = remainingDownloads;
    return this;
  }

   /**
   * Get remainingDownloads
   * @return remainingDownloads
  **/
  @javax.annotation.Nonnull

  public BigDecimal getRemainingDownloads() {
    return remainingDownloads;
  }


  public void setRemainingDownloads(BigDecimal remainingDownloads) {
    this.remainingDownloads = remainingDownloads;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Userinfo200ResponseData userinfo200ResponseData = (Userinfo200ResponseData) o;
    return Objects.equals(this.allowedDownloads, userinfo200ResponseData.allowedDownloads) &&
        Objects.equals(this.level, userinfo200ResponseData.level) &&
        Objects.equals(this.userId, userinfo200ResponseData.userId) &&
        Objects.equals(this.extInstalled, userinfo200ResponseData.extInstalled) &&
        Objects.equals(this.vip, userinfo200ResponseData.vip) &&
        Objects.equals(this.downloadsCount, userinfo200ResponseData.downloadsCount) &&
        Objects.equals(this.remainingDownloads, userinfo200ResponseData.remainingDownloads);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowedDownloads, level, userId, extInstalled, vip, downloadsCount, remainingDownloads);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Userinfo200ResponseData {\n");
    sb.append("    allowedDownloads: ").append(toIndentedString(allowedDownloads)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    extInstalled: ").append(toIndentedString(extInstalled)).append("\n");
    sb.append("    vip: ").append(toIndentedString(vip)).append("\n");
    sb.append("    downloadsCount: ").append(toIndentedString(downloadsCount)).append("\n");
    sb.append("    remainingDownloads: ").append(toIndentedString(remainingDownloads)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

