/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-26T20:07:01.076156+02:00[Europe/Amsterdam]")
public class Download200Response {
  public static final String SERIALIZED_NAME_LINK = "link";
  @SerializedName(SERIALIZED_NAME_LINK)
  private String link;

  public static final String SERIALIZED_NAME_FILE_NAME = "file_name";
  @SerializedName(SERIALIZED_NAME_FILE_NAME)
  private String fileName;

  public static final String SERIALIZED_NAME_REQUESTS = "requests";
  @SerializedName(SERIALIZED_NAME_REQUESTS)
  private BigDecimal requests;

  public static final String SERIALIZED_NAME_REMAINING = "remaining";
  @SerializedName(SERIALIZED_NAME_REMAINING)
  private BigDecimal remaining;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_RESET_TIME = "reset_time";
  @SerializedName(SERIALIZED_NAME_RESET_TIME)
  private String resetTime;

  public static final String SERIALIZED_NAME_RESET_TIME_UTC = "reset_time_utc";
  @SerializedName(SERIALIZED_NAME_RESET_TIME_UTC)
  private String resetTimeUtc;

  public Download200Response() {
  }

  public Download200Response link(String link) {
    
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @javax.annotation.Nonnull

  public String getLink() {
    return link;
  }


  public void setLink(String link) {
    this.link = link;
  }


  public Download200Response fileName(String fileName) {
    
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName
  **/
  @javax.annotation.Nonnull

  public String getFileName() {
    return fileName;
  }


  public void setFileName(String fileName) {
    this.fileName = fileName;
  }


  public Download200Response requests(BigDecimal requests) {
    
    this.requests = requests;
    return this;
  }

   /**
   * Get requests
   * @return requests
  **/
  @javax.annotation.Nonnull

  public BigDecimal getRequests() {
    return requests;
  }


  public void setRequests(BigDecimal requests) {
    this.requests = requests;
  }


  public Download200Response remaining(BigDecimal remaining) {
    
    this.remaining = remaining;
    return this;
  }

   /**
   * Get remaining
   * @return remaining
  **/
  @javax.annotation.Nonnull

  public BigDecimal getRemaining() {
    return remaining;
  }


  public void setRemaining(BigDecimal remaining) {
    this.remaining = remaining;
  }


  public Download200Response message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @javax.annotation.Nonnull

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public Download200Response resetTime(String resetTime) {
    
    this.resetTime = resetTime;
    return this;
  }

   /**
   * Get resetTime
   * @return resetTime
  **/
  @javax.annotation.Nonnull

  public String getResetTime() {
    return resetTime;
  }


  public void setResetTime(String resetTime) {
    this.resetTime = resetTime;
  }


  public Download200Response resetTimeUtc(String resetTimeUtc) {
    
    this.resetTimeUtc = resetTimeUtc;
    return this;
  }

   /**
   * Get resetTimeUtc
   * @return resetTimeUtc
  **/
  @javax.annotation.Nonnull

  public String getResetTimeUtc() {
    return resetTimeUtc;
  }


  public void setResetTimeUtc(String resetTimeUtc) {
    this.resetTimeUtc = resetTimeUtc;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Download200Response download200Response = (Download200Response) o;
    return Objects.equals(this.link, download200Response.link) &&
        Objects.equals(this.fileName, download200Response.fileName) &&
        Objects.equals(this.requests, download200Response.requests) &&
        Objects.equals(this.remaining, download200Response.remaining) &&
        Objects.equals(this.message, download200Response.message) &&
        Objects.equals(this.resetTime, download200Response.resetTime) &&
        Objects.equals(this.resetTimeUtc, download200Response.resetTimeUtc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(link, fileName, requests, remaining, message, resetTime, resetTimeUtc);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Download200Response {\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    requests: ").append(toIndentedString(requests)).append("\n");
    sb.append("    remaining: ").append(toIndentedString(remaining)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    resetTime: ").append(toIndentedString(resetTime)).append("\n");
    sb.append("    resetTimeUtc: ").append(toIndentedString(resetTimeUtc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

