/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.LinkedHashSet;
import java.util.Set;
import org.openapitools.client.model.Latest200ResponseDataInnerAttributesFeatureDetails;
import org.openapitools.client.model.Latest200ResponseDataInnerAttributesFilesInner;
import org.openapitools.client.model.Latest200ResponseDataInnerAttributesRelatedLinks;
import org.openapitools.client.model.Latest200ResponseDataInnerAttributesUploader;

/**
 * Latest200ResponseDataInnerAttributes
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-26T20:07:01.076156+02:00[Europe/Amsterdam]")
public class Latest200ResponseDataInnerAttributes {
  public static final String SERIALIZED_NAME_SUBTITLE_ID = "subtitle_id";
  @SerializedName(SERIALIZED_NAME_SUBTITLE_ID)
  private String subtitleId;

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  private String language;

  public static final String SERIALIZED_NAME_DOWNLOAD_COUNT = "download_count";
  @SerializedName(SERIALIZED_NAME_DOWNLOAD_COUNT)
  private BigDecimal downloadCount;

  public static final String SERIALIZED_NAME_NEW_DOWNLOAD_COUNT = "new_download_count";
  @SerializedName(SERIALIZED_NAME_NEW_DOWNLOAD_COUNT)
  private BigDecimal newDownloadCount;

  public static final String SERIALIZED_NAME_HEARING_IMPAIRED = "hearing_impaired";
  @SerializedName(SERIALIZED_NAME_HEARING_IMPAIRED)
  private Boolean hearingImpaired;

  public static final String SERIALIZED_NAME_HD = "hd";
  @SerializedName(SERIALIZED_NAME_HD)
  private Boolean hd;

  public static final String SERIALIZED_NAME_FORMAT = "format";
  @SerializedName(SERIALIZED_NAME_FORMAT)
  private Object format;

  public static final String SERIALIZED_NAME_FPS = "fps";
  @SerializedName(SERIALIZED_NAME_FPS)
  private BigDecimal fps;

  public static final String SERIALIZED_NAME_VOTES = "votes";
  @SerializedName(SERIALIZED_NAME_VOTES)
  private BigDecimal votes;

  public static final String SERIALIZED_NAME_POINTS = "points";
  @SerializedName(SERIALIZED_NAME_POINTS)
  private BigDecimal points;

  public static final String SERIALIZED_NAME_RATINGS = "ratings";
  @SerializedName(SERIALIZED_NAME_RATINGS)
  private BigDecimal ratings;

  public static final String SERIALIZED_NAME_FROM_TRUSTED = "from_trusted";
  @SerializedName(SERIALIZED_NAME_FROM_TRUSTED)
  private Boolean fromTrusted;

  public static final String SERIALIZED_NAME_FOREIGN_PARTS_ONLY = "foreign_parts_only";
  @SerializedName(SERIALIZED_NAME_FOREIGN_PARTS_ONLY)
  private Boolean foreignPartsOnly;

  public static final String SERIALIZED_NAME_AI_TRANSLATED = "ai_translated";
  @SerializedName(SERIALIZED_NAME_AI_TRANSLATED)
  private Boolean aiTranslated;

  public static final String SERIALIZED_NAME_MACHINE_TRANSLATED = "machine_translated";
  @SerializedName(SERIALIZED_NAME_MACHINE_TRANSLATED)
  private Object machineTranslated;

  public static final String SERIALIZED_NAME_UPLOAD_DATE = "upload_date";
  @SerializedName(SERIALIZED_NAME_UPLOAD_DATE)
  private String uploadDate;

  public static final String SERIALIZED_NAME_RELEASE = "release";
  @SerializedName(SERIALIZED_NAME_RELEASE)
  private String release;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  private String comments;

  public static final String SERIALIZED_NAME_LEGACY_SUBTITLE_ID = "legacy_subtitle_id";
  @SerializedName(SERIALIZED_NAME_LEGACY_SUBTITLE_ID)
  private BigDecimal legacySubtitleId;

  public static final String SERIALIZED_NAME_UPLOADER = "uploader";
  @SerializedName(SERIALIZED_NAME_UPLOADER)
  private Latest200ResponseDataInnerAttributesUploader uploader;

  public static final String SERIALIZED_NAME_FEATURE_DETAILS = "feature_details";
  @SerializedName(SERIALIZED_NAME_FEATURE_DETAILS)
  private Latest200ResponseDataInnerAttributesFeatureDetails featureDetails;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_RELATED_LINKS = "related_links";
  @SerializedName(SERIALIZED_NAME_RELATED_LINKS)
  private Latest200ResponseDataInnerAttributesRelatedLinks relatedLinks;

  public static final String SERIALIZED_NAME_FILES = "files";
  @SerializedName(SERIALIZED_NAME_FILES)
  private Set<Latest200ResponseDataInnerAttributesFilesInner> files = new LinkedHashSet<>();

  public Latest200ResponseDataInnerAttributes() {
  }

  public Latest200ResponseDataInnerAttributes subtitleId(String subtitleId) {
    
    this.subtitleId = subtitleId;
    return this;
  }

   /**
   * Get subtitleId
   * @return subtitleId
  **/
  @javax.annotation.Nonnull

  public String getSubtitleId() {
    return subtitleId;
  }


  public void setSubtitleId(String subtitleId) {
    this.subtitleId = subtitleId;
  }


  public Latest200ResponseDataInnerAttributes language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @javax.annotation.Nonnull

  public String getLanguage() {
    return language;
  }


  public void setLanguage(String language) {
    this.language = language;
  }


  public Latest200ResponseDataInnerAttributes downloadCount(BigDecimal downloadCount) {
    
    this.downloadCount = downloadCount;
    return this;
  }

   /**
   * Get downloadCount
   * @return downloadCount
  **/
  @javax.annotation.Nonnull

  public BigDecimal getDownloadCount() {
    return downloadCount;
  }


  public void setDownloadCount(BigDecimal downloadCount) {
    this.downloadCount = downloadCount;
  }


  public Latest200ResponseDataInnerAttributes newDownloadCount(BigDecimal newDownloadCount) {
    
    this.newDownloadCount = newDownloadCount;
    return this;
  }

   /**
   * Get newDownloadCount
   * @return newDownloadCount
  **/
  @javax.annotation.Nonnull

  public BigDecimal getNewDownloadCount() {
    return newDownloadCount;
  }


  public void setNewDownloadCount(BigDecimal newDownloadCount) {
    this.newDownloadCount = newDownloadCount;
  }


  public Latest200ResponseDataInnerAttributes hearingImpaired(Boolean hearingImpaired) {
    
    this.hearingImpaired = hearingImpaired;
    return this;
  }

   /**
   * Get hearingImpaired
   * @return hearingImpaired
  **/
  @javax.annotation.Nonnull

  public Boolean getHearingImpaired() {
    return hearingImpaired;
  }


  public void setHearingImpaired(Boolean hearingImpaired) {
    this.hearingImpaired = hearingImpaired;
  }


  public Latest200ResponseDataInnerAttributes hd(Boolean hd) {
    
    this.hd = hd;
    return this;
  }

   /**
   * Get hd
   * @return hd
  **/
  @javax.annotation.Nonnull

  public Boolean getHd() {
    return hd;
  }


  public void setHd(Boolean hd) {
    this.hd = hd;
  }


  public Latest200ResponseDataInnerAttributes format(Object format) {
    
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @javax.annotation.Nullable

  public Object getFormat() {
    return format;
  }


  public void setFormat(Object format) {
    this.format = format;
  }


  public Latest200ResponseDataInnerAttributes fps(BigDecimal fps) {
    
    this.fps = fps;
    return this;
  }

   /**
   * Get fps
   * @return fps
  **/
  @javax.annotation.Nonnull

  public BigDecimal getFps() {
    return fps;
  }


  public void setFps(BigDecimal fps) {
    this.fps = fps;
  }


  public Latest200ResponseDataInnerAttributes votes(BigDecimal votes) {
    
    this.votes = votes;
    return this;
  }

   /**
   * Get votes
   * @return votes
  **/
  @javax.annotation.Nonnull

  public BigDecimal getVotes() {
    return votes;
  }


  public void setVotes(BigDecimal votes) {
    this.votes = votes;
  }


  public Latest200ResponseDataInnerAttributes points(BigDecimal points) {
    
    this.points = points;
    return this;
  }

   /**
   * Get points
   * @return points
  **/
  @javax.annotation.Nonnull

  public BigDecimal getPoints() {
    return points;
  }


  public void setPoints(BigDecimal points) {
    this.points = points;
  }


  public Latest200ResponseDataInnerAttributes ratings(BigDecimal ratings) {
    
    this.ratings = ratings;
    return this;
  }

   /**
   * Get ratings
   * @return ratings
  **/
  @javax.annotation.Nonnull

  public BigDecimal getRatings() {
    return ratings;
  }


  public void setRatings(BigDecimal ratings) {
    this.ratings = ratings;
  }


  public Latest200ResponseDataInnerAttributes fromTrusted(Boolean fromTrusted) {
    
    this.fromTrusted = fromTrusted;
    return this;
  }

   /**
   * Get fromTrusted
   * @return fromTrusted
  **/
  @javax.annotation.Nonnull

  public Boolean getFromTrusted() {
    return fromTrusted;
  }


  public void setFromTrusted(Boolean fromTrusted) {
    this.fromTrusted = fromTrusted;
  }


  public Latest200ResponseDataInnerAttributes foreignPartsOnly(Boolean foreignPartsOnly) {
    
    this.foreignPartsOnly = foreignPartsOnly;
    return this;
  }

   /**
   * Get foreignPartsOnly
   * @return foreignPartsOnly
  **/
  @javax.annotation.Nonnull

  public Boolean getForeignPartsOnly() {
    return foreignPartsOnly;
  }


  public void setForeignPartsOnly(Boolean foreignPartsOnly) {
    this.foreignPartsOnly = foreignPartsOnly;
  }


  public Latest200ResponseDataInnerAttributes aiTranslated(Boolean aiTranslated) {
    
    this.aiTranslated = aiTranslated;
    return this;
  }

   /**
   * Get aiTranslated
   * @return aiTranslated
  **/
  @javax.annotation.Nonnull

  public Boolean getAiTranslated() {
    return aiTranslated;
  }


  public void setAiTranslated(Boolean aiTranslated) {
    this.aiTranslated = aiTranslated;
  }


  public Latest200ResponseDataInnerAttributes machineTranslated(Object machineTranslated) {
    
    this.machineTranslated = machineTranslated;
    return this;
  }

   /**
   * Get machineTranslated
   * @return machineTranslated
  **/
  @javax.annotation.Nullable

  public Object getMachineTranslated() {
    return machineTranslated;
  }


  public void setMachineTranslated(Object machineTranslated) {
    this.machineTranslated = machineTranslated;
  }


  public Latest200ResponseDataInnerAttributes uploadDate(String uploadDate) {
    
    this.uploadDate = uploadDate;
    return this;
  }

   /**
   * Get uploadDate
   * @return uploadDate
  **/
  @javax.annotation.Nonnull

  public String getUploadDate() {
    return uploadDate;
  }


  public void setUploadDate(String uploadDate) {
    this.uploadDate = uploadDate;
  }


  public Latest200ResponseDataInnerAttributes release(String release) {
    
    this.release = release;
    return this;
  }

   /**
   * Get release
   * @return release
  **/
  @javax.annotation.Nonnull

  public String getRelease() {
    return release;
  }


  public void setRelease(String release) {
    this.release = release;
  }


  public Latest200ResponseDataInnerAttributes comments(String comments) {
    
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @javax.annotation.Nonnull

  public String getComments() {
    return comments;
  }


  public void setComments(String comments) {
    this.comments = comments;
  }


  public Latest200ResponseDataInnerAttributes legacySubtitleId(BigDecimal legacySubtitleId) {
    
    this.legacySubtitleId = legacySubtitleId;
    return this;
  }

   /**
   * Get legacySubtitleId
   * @return legacySubtitleId
  **/
  @javax.annotation.Nonnull

  public BigDecimal getLegacySubtitleId() {
    return legacySubtitleId;
  }


  public void setLegacySubtitleId(BigDecimal legacySubtitleId) {
    this.legacySubtitleId = legacySubtitleId;
  }


  public Latest200ResponseDataInnerAttributes uploader(Latest200ResponseDataInnerAttributesUploader uploader) {
    
    this.uploader = uploader;
    return this;
  }

   /**
   * Get uploader
   * @return uploader
  **/
  @javax.annotation.Nonnull

  public Latest200ResponseDataInnerAttributesUploader getUploader() {
    return uploader;
  }


  public void setUploader(Latest200ResponseDataInnerAttributesUploader uploader) {
    this.uploader = uploader;
  }


  public Latest200ResponseDataInnerAttributes featureDetails(Latest200ResponseDataInnerAttributesFeatureDetails featureDetails) {
    
    this.featureDetails = featureDetails;
    return this;
  }

   /**
   * Get featureDetails
   * @return featureDetails
  **/
  @javax.annotation.Nonnull

  public Latest200ResponseDataInnerAttributesFeatureDetails getFeatureDetails() {
    return featureDetails;
  }


  public void setFeatureDetails(Latest200ResponseDataInnerAttributesFeatureDetails featureDetails) {
    this.featureDetails = featureDetails;
  }


  public Latest200ResponseDataInnerAttributes url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nonnull

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public Latest200ResponseDataInnerAttributes relatedLinks(Latest200ResponseDataInnerAttributesRelatedLinks relatedLinks) {
    
    this.relatedLinks = relatedLinks;
    return this;
  }

   /**
   * Get relatedLinks
   * @return relatedLinks
  **/
  @javax.annotation.Nonnull

  public Latest200ResponseDataInnerAttributesRelatedLinks getRelatedLinks() {
    return relatedLinks;
  }


  public void setRelatedLinks(Latest200ResponseDataInnerAttributesRelatedLinks relatedLinks) {
    this.relatedLinks = relatedLinks;
  }


  public Latest200ResponseDataInnerAttributes files(Set<Latest200ResponseDataInnerAttributesFilesInner> files) {
    
    this.files = files;
    return this;
  }

  public Latest200ResponseDataInnerAttributes addFilesItem(Latest200ResponseDataInnerAttributesFilesInner filesItem) {
    if (this.files == null) {
      this.files = new LinkedHashSet<>();
    }
    this.files.add(filesItem);
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  @javax.annotation.Nonnull

  public Set<Latest200ResponseDataInnerAttributesFilesInner> getFiles() {
    return files;
  }


  public void setFiles(Set<Latest200ResponseDataInnerAttributesFilesInner> files) {
    this.files = files;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Latest200ResponseDataInnerAttributes latest200ResponseDataInnerAttributes = (Latest200ResponseDataInnerAttributes) o;
    return Objects.equals(this.subtitleId, latest200ResponseDataInnerAttributes.subtitleId) &&
        Objects.equals(this.language, latest200ResponseDataInnerAttributes.language) &&
        Objects.equals(this.downloadCount, latest200ResponseDataInnerAttributes.downloadCount) &&
        Objects.equals(this.newDownloadCount, latest200ResponseDataInnerAttributes.newDownloadCount) &&
        Objects.equals(this.hearingImpaired, latest200ResponseDataInnerAttributes.hearingImpaired) &&
        Objects.equals(this.hd, latest200ResponseDataInnerAttributes.hd) &&
        Objects.equals(this.format, latest200ResponseDataInnerAttributes.format) &&
        Objects.equals(this.fps, latest200ResponseDataInnerAttributes.fps) &&
        Objects.equals(this.votes, latest200ResponseDataInnerAttributes.votes) &&
        Objects.equals(this.points, latest200ResponseDataInnerAttributes.points) &&
        Objects.equals(this.ratings, latest200ResponseDataInnerAttributes.ratings) &&
        Objects.equals(this.fromTrusted, latest200ResponseDataInnerAttributes.fromTrusted) &&
        Objects.equals(this.foreignPartsOnly, latest200ResponseDataInnerAttributes.foreignPartsOnly) &&
        Objects.equals(this.aiTranslated, latest200ResponseDataInnerAttributes.aiTranslated) &&
        Objects.equals(this.machineTranslated, latest200ResponseDataInnerAttributes.machineTranslated) &&
        Objects.equals(this.uploadDate, latest200ResponseDataInnerAttributes.uploadDate) &&
        Objects.equals(this.release, latest200ResponseDataInnerAttributes.release) &&
        Objects.equals(this.comments, latest200ResponseDataInnerAttributes.comments) &&
        Objects.equals(this.legacySubtitleId, latest200ResponseDataInnerAttributes.legacySubtitleId) &&
        Objects.equals(this.uploader, latest200ResponseDataInnerAttributes.uploader) &&
        Objects.equals(this.featureDetails, latest200ResponseDataInnerAttributes.featureDetails) &&
        Objects.equals(this.url, latest200ResponseDataInnerAttributes.url) &&
        Objects.equals(this.relatedLinks, latest200ResponseDataInnerAttributes.relatedLinks) &&
        Objects.equals(this.files, latest200ResponseDataInnerAttributes.files);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subtitleId, language, downloadCount, newDownloadCount, hearingImpaired, hd, format, fps, votes, points, ratings, fromTrusted, foreignPartsOnly, aiTranslated, machineTranslated, uploadDate, release, comments, legacySubtitleId, uploader, featureDetails, url, relatedLinks, files);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Latest200ResponseDataInnerAttributes {\n");
    sb.append("    subtitleId: ").append(toIndentedString(subtitleId)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    downloadCount: ").append(toIndentedString(downloadCount)).append("\n");
    sb.append("    newDownloadCount: ").append(toIndentedString(newDownloadCount)).append("\n");
    sb.append("    hearingImpaired: ").append(toIndentedString(hearingImpaired)).append("\n");
    sb.append("    hd: ").append(toIndentedString(hd)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    fps: ").append(toIndentedString(fps)).append("\n");
    sb.append("    votes: ").append(toIndentedString(votes)).append("\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("    ratings: ").append(toIndentedString(ratings)).append("\n");
    sb.append("    fromTrusted: ").append(toIndentedString(fromTrusted)).append("\n");
    sb.append("    foreignPartsOnly: ").append(toIndentedString(foreignPartsOnly)).append("\n");
    sb.append("    aiTranslated: ").append(toIndentedString(aiTranslated)).append("\n");
    sb.append("    machineTranslated: ").append(toIndentedString(machineTranslated)).append("\n");
    sb.append("    uploadDate: ").append(toIndentedString(uploadDate)).append("\n");
    sb.append("    release: ").append(toIndentedString(release)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    legacySubtitleId: ").append(toIndentedString(legacySubtitleId)).append("\n");
    sb.append("    uploader: ").append(toIndentedString(uploader)).append("\n");
    sb.append("    featureDetails: ").append(toIndentedString(featureDetails)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    relatedLinks: ").append(toIndentedString(relatedLinks)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

