/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Login200ResponseUser
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-26T20:07:01.076156+02:00[Europe/Amsterdam]")
public class Login200ResponseUser {
  public static final String SERIALIZED_NAME_ALLOWED_TRANSLATIONS = "allowed_translations";
  @SerializedName(SERIALIZED_NAME_ALLOWED_TRANSLATIONS)
  private BigDecimal allowedTranslations;

  public static final String SERIALIZED_NAME_ALLOWED_DOWNLOADS = "allowed_downloads";
  @SerializedName(SERIALIZED_NAME_ALLOWED_DOWNLOADS)
  private BigDecimal allowedDownloads;

  public static final String SERIALIZED_NAME_LEVEL = "level";
  @SerializedName(SERIALIZED_NAME_LEVEL)
  private String level;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private BigDecimal userId;

  public static final String SERIALIZED_NAME_EXT_INSTALLED = "ext_installed";
  @SerializedName(SERIALIZED_NAME_EXT_INSTALLED)
  private Boolean extInstalled;

  public static final String SERIALIZED_NAME_VIP = "vip";
  @SerializedName(SERIALIZED_NAME_VIP)
  private Boolean vip;

  public Login200ResponseUser() {
  }

  public Login200ResponseUser allowedTranslations(BigDecimal allowedTranslations) {
    
    this.allowedTranslations = allowedTranslations;
    return this;
  }

   /**
   * Get allowedTranslations
   * @return allowedTranslations
  **/
  @javax.annotation.Nonnull

  public BigDecimal getAllowedTranslations() {
    return allowedTranslations;
  }


  public void setAllowedTranslations(BigDecimal allowedTranslations) {
    this.allowedTranslations = allowedTranslations;
  }


  public Login200ResponseUser allowedDownloads(BigDecimal allowedDownloads) {
    
    this.allowedDownloads = allowedDownloads;
    return this;
  }

   /**
   * Get allowedDownloads
   * @return allowedDownloads
  **/
  @javax.annotation.Nonnull

  public BigDecimal getAllowedDownloads() {
    return allowedDownloads;
  }


  public void setAllowedDownloads(BigDecimal allowedDownloads) {
    this.allowedDownloads = allowedDownloads;
  }


  public Login200ResponseUser level(String level) {
    
    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  @javax.annotation.Nonnull

  public String getLevel() {
    return level;
  }


  public void setLevel(String level) {
    this.level = level;
  }


  public Login200ResponseUser userId(BigDecimal userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nonnull

  public BigDecimal getUserId() {
    return userId;
  }


  public void setUserId(BigDecimal userId) {
    this.userId = userId;
  }


  public Login200ResponseUser extInstalled(Boolean extInstalled) {
    
    this.extInstalled = extInstalled;
    return this;
  }

   /**
   * Get extInstalled
   * @return extInstalled
  **/
  @javax.annotation.Nonnull

  public Boolean getExtInstalled() {
    return extInstalled;
  }


  public void setExtInstalled(Boolean extInstalled) {
    this.extInstalled = extInstalled;
  }


  public Login200ResponseUser vip(Boolean vip) {
    
    this.vip = vip;
    return this;
  }

   /**
   * Get vip
   * @return vip
  **/
  @javax.annotation.Nonnull

  public Boolean getVip() {
    return vip;
  }


  public void setVip(Boolean vip) {
    this.vip = vip;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Login200ResponseUser login200ResponseUser = (Login200ResponseUser) o;
    return Objects.equals(this.allowedTranslations, login200ResponseUser.allowedTranslations) &&
        Objects.equals(this.allowedDownloads, login200ResponseUser.allowedDownloads) &&
        Objects.equals(this.level, login200ResponseUser.level) &&
        Objects.equals(this.userId, login200ResponseUser.userId) &&
        Objects.equals(this.extInstalled, login200ResponseUser.extInstalled) &&
        Objects.equals(this.vip, login200ResponseUser.vip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowedTranslations, allowedDownloads, level, userId, extInstalled, vip);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Login200ResponseUser {\n");
    sb.append("    allowedTranslations: ").append(toIndentedString(allowedTranslations)).append("\n");
    sb.append("    allowedDownloads: ").append(toIndentedString(allowedDownloads)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    extInstalled: ").append(toIndentedString(extInstalled)).append("\n");
    sb.append("    vip: ").append(toIndentedString(vip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

