/*
 * OpenSubtitles API
 * Explore subtitles API here
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@opensubtitles.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * SubtitleAttributesUploader
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-26T20:07:01.076156+02:00[Europe/Amsterdam]")
public class SubtitleAttributesUploader {
  public static final String SERIALIZED_NAME_UPLOADER_ID = "uploader_id";
  @SerializedName(SERIALIZED_NAME_UPLOADER_ID)
  private BigDecimal uploaderId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_RANK = "rank";
  @SerializedName(SERIALIZED_NAME_RANK)
  private String rank;

  public SubtitleAttributesUploader() {
  }

  public SubtitleAttributesUploader uploaderId(BigDecimal uploaderId) {
    
    this.uploaderId = uploaderId;
    return this;
  }

   /**
   * Get uploaderId
   * @return uploaderId
  **/
  @javax.annotation.Nullable

  public BigDecimal getUploaderId() {
    return uploaderId;
  }


  public void setUploaderId(BigDecimal uploaderId) {
    this.uploaderId = uploaderId;
  }


  public SubtitleAttributesUploader name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public SubtitleAttributesUploader rank(String rank) {
    
    this.rank = rank;
    return this;
  }

   /**
   * Get rank
   * @return rank
  **/
  @javax.annotation.Nonnull

  public String getRank() {
    return rank;
  }


  public void setRank(String rank) {
    this.rank = rank;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubtitleAttributesUploader subtitleAttributesUploader = (SubtitleAttributesUploader) o;
    return Objects.equals(this.uploaderId, subtitleAttributesUploader.uploaderId) &&
        Objects.equals(this.name, subtitleAttributesUploader.name) &&
        Objects.equals(this.rank, subtitleAttributesUploader.rank);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uploaderId, name, rank);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubtitleAttributesUploader {\n");
    sb.append("    uploaderId: ").append(toIndentedString(uploaderId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

